#!/usr/bin/env python3
"""
build.py — regenerates gm/data.js and public/data.js from the master data.json,
and keeps the shared CSS/JS in sync in both folders so each folder is fully
self-contained and independently deployable.

Run this after editing data.json by hand, or after using the GM edition's
"Export data.json" button and saving the result over data.json.

Usage:
    python3 build.py                 # just rebuild gm/ and public/
    python3 build.py --deploy        # rebuild, then push public/ to GitHub Pages
                                      # (one-time setup required — see README)
"""
import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).parent
MASTER = ROOT / "data.json"
SRC = ROOT / "src"
GM_DIR = ROOT / "gm"
PUBLIC_DIR = ROOT / "public"

SECRET_FIELD = "secret"


def load_master():
    with open(MASTER, "r") as f:
        return json.load(f)


def write_data_js(data, path, strip_secrets):
    out = json.loads(json.dumps(data))  # deep copy
    out.setdefault("entities", {})
    if strip_secrets:
        for hex_data in out["hexes"].values():
            hex_data.pop(SECRET_FIELD, None)
            # Fog of war: hexes not yet revealed to players are reduced to
            # just the revealed flag (+ rumours, see below). No terrain,
            # name, or notes leak until the GM marks them revealed and
            # re-runs this script.
            if not hex_data.get("revealed"):
                for field in ("terrain", "name", "notes", "population", "poi"):
                    hex_data.pop(field, None)
                hex_data["revealed"] = False
                # Rumours are deliberately exempt from fog of war: they're
                # things NPCs told the party about land they haven't been
                # to yet, so they're meant to show up on unexplored hexes
                # too. Drop the key entirely if there's nothing recorded,
                # so empty hexes don't carry a pointless empty string.
                if not hex_data.get("rumours"):
                    hex_data.pop("rumours", None)

        # Entities (NPCs/events/locations): only ship ones that are revealed,
        # placed on the map, AND sitting on a hex that's itself revealed —
        # otherwise a "revealed" NPC would leak the existence of a spot on
        # the map the players haven't discovered yet. Everything else,
        # including names, is simply absent from the public file.
        visible_entities = {}
        for eid, e in out["entities"].items():
            hex_key = e.get("hex")
            hex_revealed = bool(hex_key and out["hexes"].get(hex_key, {}).get("revealed"))
            if e.get("revealed") and hex_revealed:
                e = dict(e)
                e.pop(SECRET_FIELD, None)
                visible_entities[eid] = e
        out["entities"] = visible_entities
    with open(path, "w") as f:
        f.write("// Auto-generated by build.py — do not edit by hand.\n")
        f.write("const HEX_DATA = ")
        f.write(json.dumps(out, indent=1))
        f.write(";\n")


def sync_shared_assets():
    for folder in (GM_DIR, PUBLIC_DIR):
        folder.mkdir(exist_ok=True)
        shutil.copyfile(SRC / "hexmap.css", folder / "hexmap.css")
        shutil.copyfile(SRC / "hexmap-render.js", folder / "hexmap-render.js")


def git(*args, check=True):
    return subprocess.run(
        ["git", *args], cwd=ROOT, check=check,
        capture_output=True, text=True,
    )


def deploy(remote, branch):
    """
    Commit the freshly-built public/ folder and push it to `branch` on
    `remote` with `git subtree push`, which is exactly the tool for
    "publish this one subfolder as its own branch" — no separate clone,
    no extra tooling, no build output outside this repo.

    data.json and gm/data.js are excluded via .gitignore, so they're never
    part of any commit this makes, and never reach GitHub even if the repo
    itself is public.
    """
    if not (ROOT / ".git").is_dir():
        print("No git repository here yet. One-time setup:")
        print(f"  cd {ROOT}")
        print("  git init")
        print("  git add -A")
        print('  git commit -m "Initial commit"')
        print("  Then create an empty repo on GitHub and run:")
        print(f"  git remote add {remote} <your-repo-url>")
        print("  python3 build.py --deploy")
        sys.exit(1)

    remotes = git("remote").stdout.split()
    if remote not in remotes:
        print(f'No git remote named "{remote}" is configured. One-time setup:')
        print("  1. Create an empty repository on GitHub (any name, public)")
        print(f"  2. git remote add {remote} https://github.com/<you>/<repo>.git")
        print("  3. python3 build.py --deploy")
        sys.exit(1)

    status = git("status", "--porcelain").stdout
    if status.strip():
        git("add", "-A")
        commit = git("commit", "-m", "Update map", check=False)
        if commit.returncode != 0 and "nothing to commit" not in commit.stdout:
            print(commit.stdout)
            print(commit.stderr)
            sys.exit(1)
        print("Committed local changes.")
    else:
        print("Nothing to commit — public/ already matches the last build.")

    print(f"Pushing public/ to {remote}/{branch} …")
    push = subprocess.run(
        ["git", "subtree", "push", f"--prefix={PUBLIC_DIR.name}", remote, branch],
        cwd=ROOT,
    )
    if push.returncode != 0:
        print()
        print("git subtree push failed — see the git output above.")
        print("This is usually a git authentication issue (SSH key / token)")
        print("rather than anything wrong with the map itself.")
        sys.exit(1)

    url = git("remote", "get-url", remote, check=False).stdout.strip()
    print()
    print(f"Pushed to {remote}/{branch}.")
    print("If this is the first deploy, enable Pages once in GitHub:")
    print("  Repo Settings -> Pages -> Source: Deploy from a branch")
    print(f"  Branch: {branch} / (root)")
    if url:
        print(f"Repo: {url}")


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--deploy", action="store_true", help="also push public/ to GitHub Pages via git subtree")
    parser.add_argument("--remote", default="origin", help="git remote to push to (default: origin)")
    parser.add_argument("--branch", default="gh-pages", help="branch to publish (default: gh-pages)")
    args = parser.parse_args()

    data = load_master()
    n_hexes = len(data["hexes"])
    n_secrets = sum(1 for h in data["hexes"].values() if h.get(SECRET_FIELD))
    n_revealed = sum(1 for h in data["hexes"].values() if h.get("revealed"))
    n_rumours = sum(1 for h in data["hexes"].values() if h.get("rumours"))
    entities = data.get("entities", {})
    n_entities = len(entities)
    hexes = data.get("hexes", {})
    n_entities_visible = sum(
        1 for e in entities.values()
        if e.get("revealed") and e.get("hex") and hexes.get(e["hex"], {}).get("revealed")
    )

    sync_shared_assets()
    write_data_js(data, GM_DIR / "data.js", strip_secrets=False)
    write_data_js(data, PUBLIC_DIR / "data.js", strip_secrets=True)

    print(f"Loaded {n_hexes} hexes ({n_secrets} with GM secrets, {n_revealed} revealed to players, {n_rumours} with rumours) from data.json")
    print(f"Loaded {n_entities} NPCs/events/locations ({n_entities_visible} revealed + placed, will appear in public build)")
    print(f"Wrote {GM_DIR / 'data.js'}  (full data, includes secrets)")
    print(f"Wrote {PUBLIC_DIR / 'data.js'}  (secrets stripped)")
    print("Shared hexmap.css / hexmap-render.js synced into gm/ and public/")

    if args.deploy:
        print()
        deploy(args.remote, args.branch)
    else:
        print()
        print("Deploy only the public/ folder online. Keep data.json and gm/ local.")
        print("Run `python3 build.py --deploy` to push public/ to GitHub Pages.")


if __name__ == "__main__":
    main()
