// Auto-generated by build.py — do not edit by hand.
const HEX_DATA = {
 "meta": {
  "cols": 50,
  "rows": 50,
  "orientation": "flat-top",
  "offset": "odd-q",
  "hexSize": 20
 },
 "terrainColors": {
  "unknown": "#726e7d",
  "desert": "#e0c068",
  "arctic": "#e8f0f2",
  "swamp": "#b19cd9",
  "grassland": "#c9d97a",
  "forest": "#4f7942",
  "jungle": "#2f7a4f",
  "lake": "#5aa9d6",
  "coast": "#8fd0d8",
  "ocean": "#3a6ea8",
  "mountain": "#8b8680"
 },
 "hexes": {
  "0,0": {
   "revealed": false
  },
  "0,1": {
   "revealed": false
  },
  "0,2": {
   "revealed": false
  },
  "0,3": {
   "revealed": false
  },
  "0,4": {
   "revealed": false
  },
  "0,5": {
   "revealed": false
  },
  "0,6": {
   "revealed": false
  },
  "0,7": {
   "revealed": false
  },
  "0,8": {
   "revealed": false
  },
  "0,9": {
   "revealed": false
  },
  "0,10": {
   "revealed": false
  },
  "0,11": {
   "revealed": false
  },
  "0,12": {
   "revealed": false
  },
  "0,13": {
   "revealed": false
  },
  "0,14": {
   "revealed": false
  },
  "0,15": {
   "revealed": false
  },
  "0,16": {
   "revealed": false
  },
  "0,17": {
   "revealed": false
  },
  "0,18": {
   "revealed": false
  },
  "0,19": {
   "revealed": false
  },
  "0,20": {
   "revealed": false
  },
  "0,21": {
   "revealed": false
  },
  "0,22": {
   "revealed": false
  },
  "0,23": {
   "revealed": false
  },
  "0,24": {
   "revealed": false
  },
  "0,25": {
   "revealed": false
  },
  "0,26": {
   "revealed": false
  },
  "0,27": {
   "revealed": false
  },
  "0,28": {
   "revealed": false
  },
  "0,29": {
   "revealed": false
  },
  "0,30": {
   "revealed": false
  },
  "0,31": {
   "revealed": false
  },
  "0,32": {
   "revealed": false
  },
  "0,33": {
   "revealed": false
  },
  "0,34": {
   "revealed": false
  },
  "0,35": {
   "revealed": false
  },
  "0,36": {
   "revealed": false
  },
  "0,37": {
   "revealed": false
  },
  "0,38": {
   "revealed": false
  },
  "0,39": {
   "revealed": false
  },
  "0,40": {
   "revealed": false
  },
  "0,41": {
   "revealed": false
  },
  "0,42": {
   "revealed": false
  },
  "0,43": {
   "revealed": false
  },
  "0,44": {
   "revealed": false
  },
  "0,45": {
   "revealed": false
  },
  "0,46": {
   "revealed": false
  },
  "0,47": {
   "revealed": false
  },
  "0,48": {
   "revealed": false
  },
  "0,49": {
   "revealed": false
  },
  "1,0": {
   "revealed": false
  },
  "1,1": {
   "revealed": false
  },
  "1,2": {
   "revealed": false
  },
  "1,3": {
   "revealed": false
  },
  "1,4": {
   "revealed": false
  },
  "1,5": {
   "revealed": false
  },
  "1,6": {
   "revealed": false
  },
  "1,7": {
   "revealed": false
  },
  "1,8": {
   "revealed": false
  },
  "1,9": {
   "revealed": false
  },
  "1,10": {
   "revealed": false
  },
  "1,11": {
   "revealed": false
  },
  "1,12": {
   "revealed": false
  },
  "1,13": {
   "revealed": false
  },
  "1,14": {
   "revealed": false
  },
  "1,15": {
   "revealed": false
  },
  "1,16": {
   "revealed": false
  },
  "1,17": {
   "revealed": false
  },
  "1,18": {
   "revealed": false
  },
  "1,19": {
   "revealed": false
  },
  "1,20": {
   "revealed": false
  },
  "1,21": {
   "revealed": false
  },
  "1,22": {
   "revealed": false
  },
  "1,23": {
   "revealed": false
  },
  "1,24": {
   "revealed": false
  },
  "1,25": {
   "revealed": false
  },
  "1,26": {
   "revealed": false
  },
  "1,27": {
   "revealed": false
  },
  "1,28": {
   "revealed": false
  },
  "1,29": {
   "revealed": false
  },
  "1,30": {
   "revealed": false
  },
  "1,31": {
   "revealed": false
  },
  "1,32": {
   "revealed": false
  },
  "1,33": {
   "revealed": false
  },
  "1,34": {
   "revealed": false
  },
  "1,35": {
   "revealed": false
  },
  "1,36": {
   "revealed": false
  },
  "1,37": {
   "revealed": false
  },
  "1,38": {
   "revealed": false
  },
  "1,39": {
   "revealed": false
  },
  "1,40": {
   "revealed": false
  },
  "1,41": {
   "revealed": false
  },
  "1,42": {
   "revealed": false
  },
  "1,43": {
   "revealed": false
  },
  "1,44": {
   "revealed": false
  },
  "1,45": {
   "revealed": false
  },
  "1,46": {
   "revealed": false
  },
  "1,47": {
   "revealed": false
  },
  "1,48": {
   "revealed": false
  },
  "1,49": {
   "revealed": false
  },
  "2,0": {
   "revealed": false
  },
  "2,1": {
   "revealed": false
  },
  "2,2": {
   "revealed": false
  },
  "2,3": {
   "revealed": false
  },
  "2,4": {
   "revealed": false
  },
  "2,5": {
   "revealed": false
  },
  "2,6": {
   "revealed": false
  },
  "2,7": {
   "revealed": false
  },
  "2,8": {
   "revealed": false
  },
  "2,9": {
   "revealed": false
  },
  "2,10": {
   "revealed": false
  },
  "2,11": {
   "revealed": false
  },
  "2,12": {
   "revealed": false
  },
  "2,13": {
   "revealed": false
  },
  "2,14": {
   "revealed": false
  },
  "2,15": {
   "revealed": false
  },
  "2,16": {
   "revealed": false
  },
  "2,17": {
   "revealed": false
  },
  "2,18": {
   "revealed": false
  },
  "2,19": {
   "revealed": false
  },
  "2,20": {
   "revealed": false
  },
  "2,21": {
   "revealed": false
  },
  "2,22": {
   "revealed": false
  },
  "2,23": {
   "revealed": false
  },
  "2,24": {
   "revealed": false
  },
  "2,25": {
   "revealed": false
  },
  "2,26": {
   "revealed": false
  },
  "2,27": {
   "revealed": false
  },
  "2,28": {
   "revealed": false
  },
  "2,29": {
   "revealed": false
  },
  "2,30": {
   "revealed": false
  },
  "2,31": {
   "revealed": false
  },
  "2,32": {
   "revealed": false
  },
  "2,33": {
   "revealed": false
  },
  "2,34": {
   "revealed": false
  },
  "2,35": {
   "revealed": false
  },
  "2,36": {
   "revealed": false
  },
  "2,37": {
   "revealed": false
  },
  "2,38": {
   "revealed": false
  },
  "2,39": {
   "revealed": false
  },
  "2,40": {
   "revealed": false
  },
  "2,41": {
   "revealed": false
  },
  "2,42": {
   "revealed": false
  },
  "2,43": {
   "revealed": false
  },
  "2,44": {
   "revealed": false
  },
  "2,45": {
   "revealed": false
  },
  "2,46": {
   "revealed": false
  },
  "2,47": {
   "revealed": false
  },
  "2,48": {
   "revealed": false
  },
  "2,49": {
   "revealed": false
  },
  "3,0": {
   "revealed": false
  },
  "3,1": {
   "revealed": false
  },
  "3,2": {
   "revealed": false
  },
  "3,3": {
   "revealed": false
  },
  "3,4": {
   "revealed": false
  },
  "3,5": {
   "revealed": false
  },
  "3,6": {
   "revealed": false
  },
  "3,7": {
   "revealed": false
  },
  "3,8": {
   "revealed": false
  },
  "3,9": {
   "revealed": false
  },
  "3,10": {
   "revealed": false
  },
  "3,11": {
   "revealed": false
  },
  "3,12": {
   "revealed": false
  },
  "3,13": {
   "revealed": false
  },
  "3,14": {
   "revealed": false
  },
  "3,15": {
   "revealed": false
  },
  "3,16": {
   "revealed": false
  },
  "3,17": {
   "revealed": false
  },
  "3,18": {
   "revealed": false
  },
  "3,19": {
   "revealed": false
  },
  "3,20": {
   "revealed": false
  },
  "3,21": {
   "revealed": false
  },
  "3,22": {
   "revealed": false
  },
  "3,23": {
   "revealed": false
  },
  "3,24": {
   "revealed": false
  },
  "3,25": {
   "revealed": false
  },
  "3,26": {
   "revealed": false
  },
  "3,27": {
   "revealed": false
  },
  "3,28": {
   "revealed": false
  },
  "3,29": {
   "revealed": false
  },
  "3,30": {
   "revealed": false
  },
  "3,31": {
   "revealed": false
  },
  "3,32": {
   "revealed": false
  },
  "3,33": {
   "revealed": false
  },
  "3,34": {
   "revealed": false
  },
  "3,35": {
   "revealed": false
  },
  "3,36": {
   "revealed": false
  },
  "3,37": {
   "revealed": false
  },
  "3,38": {
   "revealed": false
  },
  "3,39": {
   "revealed": false
  },
  "3,40": {
   "revealed": false
  },
  "3,41": {
   "revealed": false
  },
  "3,42": {
   "revealed": false
  },
  "3,43": {
   "revealed": false
  },
  "3,44": {
   "revealed": false
  },
  "3,45": {
   "revealed": false
  },
  "3,46": {
   "revealed": false
  },
  "3,47": {
   "revealed": false
  },
  "3,48": {
   "revealed": false
  },
  "3,49": {
   "revealed": false
  },
  "4,0": {
   "revealed": false
  },
  "4,1": {
   "revealed": false
  },
  "4,2": {
   "revealed": false
  },
  "4,3": {
   "revealed": false
  },
  "4,4": {
   "revealed": false
  },
  "4,5": {
   "revealed": false
  },
  "4,6": {
   "revealed": false
  },
  "4,7": {
   "revealed": false
  },
  "4,8": {
   "revealed": false
  },
  "4,9": {
   "revealed": false
  },
  "4,10": {
   "revealed": false
  },
  "4,11": {
   "revealed": false
  },
  "4,12": {
   "revealed": false
  },
  "4,13": {
   "revealed": false
  },
  "4,14": {
   "revealed": false
  },
  "4,15": {
   "revealed": false
  },
  "4,16": {
   "revealed": false
  },
  "4,17": {
   "revealed": false
  },
  "4,18": {
   "revealed": false
  },
  "4,19": {
   "revealed": false
  },
  "4,20": {
   "revealed": false
  },
  "4,21": {
   "revealed": false
  },
  "4,22": {
   "revealed": false
  },
  "4,23": {
   "revealed": false
  },
  "4,24": {
   "revealed": false
  },
  "4,25": {
   "revealed": false
  },
  "4,26": {
   "revealed": false
  },
  "4,27": {
   "revealed": false
  },
  "4,28": {
   "revealed": false
  },
  "4,29": {
   "revealed": false
  },
  "4,30": {
   "revealed": false
  },
  "4,31": {
   "revealed": false
  },
  "4,32": {
   "revealed": false
  },
  "4,33": {
   "revealed": false
  },
  "4,34": {
   "revealed": false
  },
  "4,35": {
   "revealed": false
  },
  "4,36": {
   "revealed": false
  },
  "4,37": {
   "revealed": false
  },
  "4,38": {
   "revealed": false
  },
  "4,39": {
   "revealed": false
  },
  "4,40": {
   "revealed": false
  },
  "4,41": {
   "revealed": false
  },
  "4,42": {
   "revealed": false
  },
  "4,43": {
   "revealed": false
  },
  "4,44": {
   "revealed": false
  },
  "4,45": {
   "revealed": false
  },
  "4,46": {
   "revealed": false
  },
  "4,47": {
   "revealed": false
  },
  "4,48": {
   "revealed": false
  },
  "4,49": {
   "revealed": false
  },
  "5,0": {
   "revealed": false
  },
  "5,1": {
   "revealed": false
  },
  "5,2": {
   "revealed": false
  },
  "5,3": {
   "revealed": false
  },
  "5,4": {
   "revealed": false
  },
  "5,5": {
   "revealed": false
  },
  "5,6": {
   "revealed": false
  },
  "5,7": {
   "revealed": false
  },
  "5,8": {
   "revealed": false
  },
  "5,9": {
   "revealed": false
  },
  "5,10": {
   "revealed": false
  },
  "5,11": {
   "revealed": false
  },
  "5,12": {
   "revealed": false
  },
  "5,13": {
   "revealed": false
  },
  "5,14": {
   "revealed": false
  },
  "5,15": {
   "revealed": false
  },
  "5,16": {
   "revealed": false
  },
  "5,17": {
   "revealed": false
  },
  "5,18": {
   "revealed": false
  },
  "5,19": {
   "revealed": false
  },
  "5,20": {
   "revealed": false
  },
  "5,21": {
   "revealed": false
  },
  "5,22": {
   "revealed": false
  },
  "5,23": {
   "revealed": false
  },
  "5,24": {
   "revealed": false
  },
  "5,25": {
   "revealed": false
  },
  "5,26": {
   "revealed": false
  },
  "5,27": {
   "revealed": false
  },
  "5,28": {
   "revealed": false
  },
  "5,29": {
   "revealed": false
  },
  "5,30": {
   "revealed": false
  },
  "5,31": {
   "revealed": false
  },
  "5,32": {
   "revealed": false
  },
  "5,33": {
   "revealed": false
  },
  "5,34": {
   "revealed": false
  },
  "5,35": {
   "revealed": false
  },
  "5,36": {
   "revealed": false
  },
  "5,37": {
   "revealed": false
  },
  "5,38": {
   "revealed": false
  },
  "5,39": {
   "revealed": false
  },
  "5,40": {
   "revealed": false
  },
  "5,41": {
   "revealed": false
  },
  "5,42": {
   "revealed": false
  },
  "5,43": {
   "revealed": false
  },
  "5,44": {
   "revealed": false
  },
  "5,45": {
   "revealed": false
  },
  "5,46": {
   "revealed": false
  },
  "5,47": {
   "revealed": false
  },
  "5,48": {
   "revealed": false
  },
  "5,49": {
   "revealed": false
  },
  "6,0": {
   "revealed": false
  },
  "6,1": {
   "revealed": false
  },
  "6,2": {
   "revealed": false
  },
  "6,3": {
   "revealed": false
  },
  "6,4": {
   "revealed": false
  },
  "6,5": {
   "revealed": false
  },
  "6,6": {
   "revealed": false
  },
  "6,7": {
   "revealed": false
  },
  "6,8": {
   "revealed": false
  },
  "6,9": {
   "revealed": false
  },
  "6,10": {
   "revealed": false
  },
  "6,11": {
   "revealed": false
  },
  "6,12": {
   "revealed": false
  },
  "6,13": {
   "revealed": false
  },
  "6,14": {
   "revealed": false
  },
  "6,15": {
   "revealed": false
  },
  "6,16": {
   "revealed": false
  },
  "6,17": {
   "revealed": false
  },
  "6,18": {
   "revealed": false
  },
  "6,19": {
   "revealed": false
  },
  "6,20": {
   "revealed": false
  },
  "6,21": {
   "revealed": false
  },
  "6,22": {
   "revealed": false
  },
  "6,23": {
   "revealed": false
  },
  "6,24": {
   "revealed": false
  },
  "6,25": {
   "revealed": false
  },
  "6,26": {
   "revealed": false
  },
  "6,27": {
   "revealed": false
  },
  "6,28": {
   "revealed": false
  },
  "6,29": {
   "revealed": false
  },
  "6,30": {
   "revealed": false
  },
  "6,31": {
   "revealed": false
  },
  "6,32": {
   "revealed": false
  },
  "6,33": {
   "revealed": false
  },
  "6,34": {
   "revealed": false
  },
  "6,35": {
   "revealed": false
  },
  "6,36": {
   "revealed": false
  },
  "6,37": {
   "revealed": false
  },
  "6,38": {
   "revealed": false
  },
  "6,39": {
   "revealed": false
  },
  "6,40": {
   "revealed": false
  },
  "6,41": {
   "revealed": false
  },
  "6,42": {
   "revealed": false
  },
  "6,43": {
   "revealed": false
  },
  "6,44": {
   "revealed": false
  },
  "6,45": {
   "revealed": false
  },
  "6,46": {
   "revealed": false
  },
  "6,47": {
   "revealed": false
  },
  "6,48": {
   "revealed": false
  },
  "6,49": {
   "revealed": false
  },
  "7,0": {
   "revealed": false
  },
  "7,1": {
   "revealed": false
  },
  "7,2": {
   "revealed": false
  },
  "7,3": {
   "revealed": false
  },
  "7,4": {
   "revealed": false
  },
  "7,5": {
   "revealed": false
  },
  "7,6": {
   "revealed": false
  },
  "7,7": {
   "revealed": false
  },
  "7,8": {
   "revealed": false
  },
  "7,9": {
   "revealed": false
  },
  "7,10": {
   "revealed": false
  },
  "7,11": {
   "revealed": false
  },
  "7,12": {
   "revealed": false
  },
  "7,13": {
   "revealed": false
  },
  "7,14": {
   "revealed": false
  },
  "7,15": {
   "revealed": false
  },
  "7,16": {
   "revealed": false
  },
  "7,17": {
   "revealed": false
  },
  "7,18": {
   "revealed": false
  },
  "7,19": {
   "revealed": false
  },
  "7,20": {
   "revealed": false
  },
  "7,21": {
   "revealed": false
  },
  "7,22": {
   "revealed": false
  },
  "7,23": {
   "revealed": false
  },
  "7,24": {
   "revealed": false
  },
  "7,25": {
   "revealed": false
  },
  "7,26": {
   "revealed": false
  },
  "7,27": {
   "revealed": false
  },
  "7,28": {
   "revealed": false
  },
  "7,29": {
   "revealed": false
  },
  "7,30": {
   "revealed": false
  },
  "7,31": {
   "revealed": false
  },
  "7,32": {
   "revealed": false
  },
  "7,33": {
   "revealed": false
  },
  "7,34": {
   "revealed": false
  },
  "7,35": {
   "revealed": false
  },
  "7,36": {
   "revealed": false
  },
  "7,37": {
   "revealed": false
  },
  "7,38": {
   "revealed": false
  },
  "7,39": {
   "revealed": false
  },
  "7,40": {
   "revealed": false
  },
  "7,41": {
   "revealed": false
  },
  "7,42": {
   "revealed": false
  },
  "7,43": {
   "revealed": false
  },
  "7,44": {
   "revealed": false
  },
  "7,45": {
   "revealed": false
  },
  "7,46": {
   "revealed": false
  },
  "7,47": {
   "revealed": false
  },
  "7,48": {
   "revealed": false
  },
  "7,49": {
   "revealed": false
  },
  "8,0": {
   "revealed": false
  },
  "8,1": {
   "revealed": false
  },
  "8,2": {
   "revealed": false
  },
  "8,3": {
   "revealed": false
  },
  "8,4": {
   "revealed": false
  },
  "8,5": {
   "revealed": false
  },
  "8,6": {
   "revealed": false
  },
  "8,7": {
   "revealed": false
  },
  "8,8": {
   "revealed": false
  },
  "8,9": {
   "revealed": false
  },
  "8,10": {
   "revealed": false
  },
  "8,11": {
   "revealed": false
  },
  "8,12": {
   "revealed": false
  },
  "8,13": {
   "revealed": false
  },
  "8,14": {
   "revealed": false
  },
  "8,15": {
   "revealed": false
  },
  "8,16": {
   "revealed": false
  },
  "8,17": {
   "revealed": false
  },
  "8,18": {
   "revealed": false
  },
  "8,19": {
   "revealed": false
  },
  "8,20": {
   "revealed": false
  },
  "8,21": {
   "revealed": false
  },
  "8,22": {
   "revealed": false
  },
  "8,23": {
   "revealed": false
  },
  "8,24": {
   "revealed": false
  },
  "8,25": {
   "revealed": false
  },
  "8,26": {
   "revealed": false
  },
  "8,27": {
   "revealed": false
  },
  "8,28": {
   "revealed": false
  },
  "8,29": {
   "revealed": false
  },
  "8,30": {
   "revealed": false
  },
  "8,31": {
   "revealed": false
  },
  "8,32": {
   "revealed": false
  },
  "8,33": {
   "revealed": false
  },
  "8,34": {
   "revealed": false
  },
  "8,35": {
   "revealed": false
  },
  "8,36": {
   "revealed": false
  },
  "8,37": {
   "revealed": false
  },
  "8,38": {
   "revealed": false
  },
  "8,39": {
   "revealed": false
  },
  "8,40": {
   "revealed": false
  },
  "8,41": {
   "revealed": false
  },
  "8,42": {
   "revealed": false
  },
  "8,43": {
   "revealed": false
  },
  "8,44": {
   "revealed": false
  },
  "8,45": {
   "revealed": false
  },
  "8,46": {
   "revealed": false
  },
  "8,47": {
   "revealed": false
  },
  "8,48": {
   "revealed": false
  },
  "8,49": {
   "revealed": false
  },
  "9,0": {
   "revealed": false
  },
  "9,1": {
   "revealed": false
  },
  "9,2": {
   "revealed": false
  },
  "9,3": {
   "revealed": false
  },
  "9,4": {
   "revealed": false
  },
  "9,5": {
   "revealed": false
  },
  "9,6": {
   "revealed": false
  },
  "9,7": {
   "revealed": false
  },
  "9,8": {
   "revealed": false
  },
  "9,9": {
   "revealed": false
  },
  "9,10": {
   "revealed": false
  },
  "9,11": {
   "revealed": false
  },
  "9,12": {
   "revealed": false
  },
  "9,13": {
   "revealed": false
  },
  "9,14": {
   "revealed": false
  },
  "9,15": {
   "revealed": false
  },
  "9,16": {
   "revealed": false
  },
  "9,17": {
   "revealed": false
  },
  "9,18": {
   "revealed": false
  },
  "9,19": {
   "revealed": false
  },
  "9,20": {
   "revealed": false
  },
  "9,21": {
   "revealed": false
  },
  "9,22": {
   "revealed": false
  },
  "9,23": {
   "revealed": false
  },
  "9,24": {
   "revealed": false
  },
  "9,25": {
   "revealed": false
  },
  "9,26": {
   "revealed": false
  },
  "9,27": {
   "revealed": false
  },
  "9,28": {
   "revealed": false
  },
  "9,29": {
   "revealed": false
  },
  "9,30": {
   "revealed": false
  },
  "9,31": {
   "revealed": false
  },
  "9,32": {
   "revealed": false
  },
  "9,33": {
   "revealed": false
  },
  "9,34": {
   "revealed": false
  },
  "9,35": {
   "revealed": false
  },
  "9,36": {
   "revealed": false
  },
  "9,37": {
   "revealed": false
  },
  "9,38": {
   "revealed": false
  },
  "9,39": {
   "revealed": false
  },
  "9,40": {
   "revealed": false
  },
  "9,41": {
   "revealed": false
  },
  "9,42": {
   "revealed": false
  },
  "9,43": {
   "revealed": false
  },
  "9,44": {
   "revealed": false
  },
  "9,45": {
   "revealed": false
  },
  "9,46": {
   "revealed": false
  },
  "9,47": {
   "revealed": false
  },
  "9,48": {
   "revealed": false
  },
  "9,49": {
   "revealed": false
  },
  "10,0": {
   "revealed": false
  },
  "10,1": {
   "revealed": false
  },
  "10,2": {
   "revealed": false
  },
  "10,3": {
   "revealed": false
  },
  "10,4": {
   "revealed": false
  },
  "10,5": {
   "revealed": false
  },
  "10,6": {
   "revealed": false
  },
  "10,7": {
   "revealed": false
  },
  "10,8": {
   "revealed": false
  },
  "10,9": {
   "revealed": false
  },
  "10,10": {
   "revealed": false
  },
  "10,11": {
   "revealed": false
  },
  "10,12": {
   "revealed": false
  },
  "10,13": {
   "revealed": false
  },
  "10,14": {
   "revealed": false
  },
  "10,15": {
   "revealed": false
  },
  "10,16": {
   "revealed": false
  },
  "10,17": {
   "revealed": false
  },
  "10,18": {
   "revealed": false
  },
  "10,19": {
   "revealed": false
  },
  "10,20": {
   "revealed": false
  },
  "10,21": {
   "revealed": false
  },
  "10,22": {
   "revealed": false
  },
  "10,23": {
   "revealed": false
  },
  "10,24": {
   "revealed": false
  },
  "10,25": {
   "revealed": false
  },
  "10,26": {
   "revealed": false
  },
  "10,27": {
   "revealed": false
  },
  "10,28": {
   "revealed": false
  },
  "10,29": {
   "revealed": false
  },
  "10,30": {
   "revealed": false
  },
  "10,31": {
   "revealed": false
  },
  "10,32": {
   "revealed": false
  },
  "10,33": {
   "revealed": false
  },
  "10,34": {
   "revealed": false
  },
  "10,35": {
   "revealed": false
  },
  "10,36": {
   "revealed": false
  },
  "10,37": {
   "revealed": false
  },
  "10,38": {
   "revealed": false
  },
  "10,39": {
   "revealed": false
  },
  "10,40": {
   "revealed": false
  },
  "10,41": {
   "revealed": false
  },
  "10,42": {
   "revealed": false
  },
  "10,43": {
   "revealed": false
  },
  "10,44": {
   "revealed": false
  },
  "10,45": {
   "revealed": false
  },
  "10,46": {
   "revealed": false
  },
  "10,47": {
   "revealed": false
  },
  "10,48": {
   "revealed": false
  },
  "10,49": {
   "revealed": false
  },
  "11,0": {
   "revealed": false
  },
  "11,1": {
   "revealed": false
  },
  "11,2": {
   "revealed": false
  },
  "11,3": {
   "revealed": false
  },
  "11,4": {
   "revealed": false
  },
  "11,5": {
   "revealed": false
  },
  "11,6": {
   "revealed": false
  },
  "11,7": {
   "revealed": false
  },
  "11,8": {
   "revealed": false
  },
  "11,9": {
   "revealed": false
  },
  "11,10": {
   "revealed": false
  },
  "11,11": {
   "revealed": false
  },
  "11,12": {
   "revealed": false
  },
  "11,13": {
   "revealed": false
  },
  "11,14": {
   "revealed": false
  },
  "11,15": {
   "revealed": false
  },
  "11,16": {
   "revealed": false
  },
  "11,17": {
   "revealed": false
  },
  "11,18": {
   "revealed": false
  },
  "11,19": {
   "revealed": false
  },
  "11,20": {
   "revealed": false
  },
  "11,21": {
   "revealed": false
  },
  "11,22": {
   "revealed": false
  },
  "11,23": {
   "revealed": false
  },
  "11,24": {
   "revealed": false
  },
  "11,25": {
   "revealed": false
  },
  "11,26": {
   "revealed": false
  },
  "11,27": {
   "revealed": false
  },
  "11,28": {
   "revealed": false
  },
  "11,29": {
   "revealed": false
  },
  "11,30": {
   "revealed": false
  },
  "11,31": {
   "revealed": false
  },
  "11,32": {
   "revealed": false
  },
  "11,33": {
   "revealed": false
  },
  "11,34": {
   "revealed": false
  },
  "11,35": {
   "revealed": false
  },
  "11,36": {
   "revealed": false
  },
  "11,37": {
   "revealed": false
  },
  "11,38": {
   "revealed": false
  },
  "11,39": {
   "revealed": false
  },
  "11,40": {
   "revealed": false
  },
  "11,41": {
   "revealed": false
  },
  "11,42": {
   "revealed": false
  },
  "11,43": {
   "revealed": false
  },
  "11,44": {
   "revealed": false
  },
  "11,45": {
   "revealed": false
  },
  "11,46": {
   "revealed": false
  },
  "11,47": {
   "revealed": false
  },
  "11,48": {
   "revealed": false
  },
  "11,49": {
   "revealed": false
  },
  "12,0": {
   "revealed": false
  },
  "12,1": {
   "revealed": false
  },
  "12,2": {
   "revealed": false
  },
  "12,3": {
   "revealed": false
  },
  "12,4": {
   "revealed": false
  },
  "12,5": {
   "revealed": false
  },
  "12,6": {
   "revealed": false
  },
  "12,7": {
   "revealed": false
  },
  "12,8": {
   "revealed": false
  },
  "12,9": {
   "revealed": false
  },
  "12,10": {
   "revealed": false
  },
  "12,11": {
   "revealed": false
  },
  "12,12": {
   "revealed": false
  },
  "12,13": {
   "revealed": false
  },
  "12,14": {
   "revealed": false
  },
  "12,15": {
   "revealed": false
  },
  "12,16": {
   "revealed": false
  },
  "12,17": {
   "revealed": false
  },
  "12,18": {
   "revealed": false
  },
  "12,19": {
   "revealed": false
  },
  "12,20": {
   "revealed": false
  },
  "12,21": {
   "revealed": false
  },
  "12,22": {
   "revealed": false
  },
  "12,23": {
   "revealed": false
  },
  "12,24": {
   "revealed": false
  },
  "12,25": {
   "revealed": false
  },
  "12,26": {
   "revealed": false
  },
  "12,27": {
   "revealed": false
  },
  "12,28": {
   "revealed": false
  },
  "12,29": {
   "revealed": false
  },
  "12,30": {
   "revealed": false
  },
  "12,31": {
   "revealed": false
  },
  "12,32": {
   "revealed": false
  },
  "12,33": {
   "revealed": false
  },
  "12,34": {
   "revealed": false
  },
  "12,35": {
   "revealed": false
  },
  "12,36": {
   "revealed": false
  },
  "12,37": {
   "revealed": false
  },
  "12,38": {
   "revealed": false
  },
  "12,39": {
   "revealed": false
  },
  "12,40": {
   "revealed": false
  },
  "12,41": {
   "revealed": false
  },
  "12,42": {
   "revealed": false
  },
  "12,43": {
   "revealed": false
  },
  "12,44": {
   "revealed": false
  },
  "12,45": {
   "revealed": false
  },
  "12,46": {
   "revealed": false
  },
  "12,47": {
   "revealed": false
  },
  "12,48": {
   "revealed": false
  },
  "12,49": {
   "revealed": false
  },
  "13,0": {
   "revealed": false
  },
  "13,1": {
   "revealed": false
  },
  "13,2": {
   "revealed": false
  },
  "13,3": {
   "revealed": false
  },
  "13,4": {
   "revealed": false
  },
  "13,5": {
   "revealed": false
  },
  "13,6": {
   "revealed": false
  },
  "13,7": {
   "revealed": false
  },
  "13,8": {
   "revealed": false
  },
  "13,9": {
   "revealed": false
  },
  "13,10": {
   "revealed": false
  },
  "13,11": {
   "revealed": false
  },
  "13,12": {
   "revealed": false
  },
  "13,13": {
   "revealed": false
  },
  "13,14": {
   "revealed": false
  },
  "13,15": {
   "revealed": false
  },
  "13,16": {
   "revealed": false
  },
  "13,17": {
   "revealed": false
  },
  "13,18": {
   "revealed": false
  },
  "13,19": {
   "revealed": false
  },
  "13,20": {
   "revealed": false
  },
  "13,21": {
   "revealed": false
  },
  "13,22": {
   "revealed": false
  },
  "13,23": {
   "revealed": false
  },
  "13,24": {
   "revealed": false
  },
  "13,25": {
   "revealed": false
  },
  "13,26": {
   "revealed": false
  },
  "13,27": {
   "revealed": false
  },
  "13,28": {
   "revealed": false
  },
  "13,29": {
   "revealed": false
  },
  "13,30": {
   "revealed": false
  },
  "13,31": {
   "revealed": false
  },
  "13,32": {
   "revealed": false
  },
  "13,33": {
   "revealed": false
  },
  "13,34": {
   "revealed": false
  },
  "13,35": {
   "revealed": false
  },
  "13,36": {
   "revealed": false
  },
  "13,37": {
   "revealed": false
  },
  "13,38": {
   "revealed": false
  },
  "13,39": {
   "revealed": false
  },
  "13,40": {
   "revealed": false
  },
  "13,41": {
   "revealed": false
  },
  "13,42": {
   "revealed": false
  },
  "13,43": {
   "revealed": false
  },
  "13,44": {
   "revealed": false
  },
  "13,45": {
   "revealed": false
  },
  "13,46": {
   "revealed": false
  },
  "13,47": {
   "revealed": false
  },
  "13,48": {
   "revealed": false
  },
  "13,49": {
   "revealed": false
  },
  "14,0": {
   "revealed": false
  },
  "14,1": {
   "revealed": false
  },
  "14,2": {
   "revealed": false
  },
  "14,3": {
   "revealed": false
  },
  "14,4": {
   "revealed": false
  },
  "14,5": {
   "revealed": false
  },
  "14,6": {
   "revealed": false
  },
  "14,7": {
   "revealed": false
  },
  "14,8": {
   "revealed": false
  },
  "14,9": {
   "revealed": false
  },
  "14,10": {
   "revealed": false
  },
  "14,11": {
   "revealed": false
  },
  "14,12": {
   "revealed": false
  },
  "14,13": {
   "revealed": false
  },
  "14,14": {
   "revealed": false
  },
  "14,15": {
   "revealed": false
  },
  "14,16": {
   "revealed": false
  },
  "14,17": {
   "revealed": false
  },
  "14,18": {
   "revealed": false
  },
  "14,19": {
   "revealed": false
  },
  "14,20": {
   "revealed": false
  },
  "14,21": {
   "revealed": false
  },
  "14,22": {
   "revealed": false
  },
  "14,23": {
   "revealed": false
  },
  "14,24": {
   "revealed": false
  },
  "14,25": {
   "revealed": false
  },
  "14,26": {
   "revealed": false
  },
  "14,27": {
   "revealed": false
  },
  "14,28": {
   "revealed": false
  },
  "14,29": {
   "revealed": false
  },
  "14,30": {
   "revealed": false
  },
  "14,31": {
   "revealed": false
  },
  "14,32": {
   "revealed": false
  },
  "14,33": {
   "revealed": false
  },
  "14,34": {
   "revealed": false
  },
  "14,35": {
   "revealed": false
  },
  "14,36": {
   "revealed": false
  },
  "14,37": {
   "revealed": false
  },
  "14,38": {
   "revealed": false
  },
  "14,39": {
   "revealed": false
  },
  "14,40": {
   "revealed": false
  },
  "14,41": {
   "revealed": false
  },
  "14,42": {
   "revealed": false
  },
  "14,43": {
   "revealed": false
  },
  "14,44": {
   "revealed": false
  },
  "14,45": {
   "revealed": false
  },
  "14,46": {
   "revealed": false
  },
  "14,47": {
   "revealed": false
  },
  "14,48": {
   "revealed": false
  },
  "14,49": {
   "revealed": false
  },
  "15,0": {
   "revealed": false
  },
  "15,1": {
   "revealed": false
  },
  "15,2": {
   "revealed": false
  },
  "15,3": {
   "revealed": false
  },
  "15,4": {
   "revealed": false
  },
  "15,5": {
   "revealed": false
  },
  "15,6": {
   "revealed": false
  },
  "15,7": {
   "revealed": false
  },
  "15,8": {
   "revealed": false
  },
  "15,9": {
   "revealed": false
  },
  "15,10": {
   "revealed": false
  },
  "15,11": {
   "revealed": false
  },
  "15,12": {
   "revealed": false
  },
  "15,13": {
   "revealed": false
  },
  "15,14": {
   "revealed": false
  },
  "15,15": {
   "revealed": false
  },
  "15,16": {
   "revealed": false
  },
  "15,17": {
   "revealed": false
  },
  "15,18": {
   "revealed": false
  },
  "15,19": {
   "revealed": false
  },
  "15,20": {
   "revealed": false
  },
  "15,21": {
   "revealed": false
  },
  "15,22": {
   "revealed": false
  },
  "15,23": {
   "revealed": false
  },
  "15,24": {
   "revealed": false
  },
  "15,25": {
   "revealed": false
  },
  "15,26": {
   "revealed": false
  },
  "15,27": {
   "revealed": false
  },
  "15,28": {
   "revealed": false
  },
  "15,29": {
   "revealed": false
  },
  "15,30": {
   "revealed": false
  },
  "15,31": {
   "revealed": false
  },
  "15,32": {
   "revealed": false
  },
  "15,33": {
   "revealed": false
  },
  "15,34": {
   "revealed": false
  },
  "15,35": {
   "revealed": false
  },
  "15,36": {
   "revealed": false
  },
  "15,37": {
   "revealed": false
  },
  "15,38": {
   "revealed": false
  },
  "15,39": {
   "revealed": false
  },
  "15,40": {
   "revealed": false
  },
  "15,41": {
   "revealed": false
  },
  "15,42": {
   "revealed": false
  },
  "15,43": {
   "revealed": false
  },
  "15,44": {
   "revealed": false
  },
  "15,45": {
   "revealed": false
  },
  "15,46": {
   "revealed": false
  },
  "15,47": {
   "revealed": false
  },
  "15,48": {
   "revealed": false
  },
  "15,49": {
   "revealed": false
  },
  "16,0": {
   "revealed": false
  },
  "16,1": {
   "revealed": false
  },
  "16,2": {
   "revealed": false
  },
  "16,3": {
   "revealed": false
  },
  "16,4": {
   "revealed": false
  },
  "16,5": {
   "revealed": false
  },
  "16,6": {
   "revealed": false
  },
  "16,7": {
   "revealed": false
  },
  "16,8": {
   "revealed": false
  },
  "16,9": {
   "revealed": false
  },
  "16,10": {
   "revealed": false
  },
  "16,11": {
   "revealed": false
  },
  "16,12": {
   "revealed": false
  },
  "16,13": {
   "revealed": false
  },
  "16,14": {
   "revealed": false
  },
  "16,15": {
   "revealed": false
  },
  "16,16": {
   "revealed": false
  },
  "16,17": {
   "revealed": false
  },
  "16,18": {
   "revealed": false
  },
  "16,19": {
   "revealed": false
  },
  "16,20": {
   "revealed": false
  },
  "16,21": {
   "revealed": false
  },
  "16,22": {
   "revealed": false
  },
  "16,23": {
   "revealed": false
  },
  "16,24": {
   "revealed": false
  },
  "16,25": {
   "revealed": false
  },
  "16,26": {
   "revealed": false
  },
  "16,27": {
   "revealed": false
  },
  "16,28": {
   "revealed": false
  },
  "16,29": {
   "revealed": false
  },
  "16,30": {
   "revealed": false
  },
  "16,31": {
   "revealed": false
  },
  "16,32": {
   "revealed": false
  },
  "16,33": {
   "revealed": false
  },
  "16,34": {
   "revealed": false
  },
  "16,35": {
   "revealed": false
  },
  "16,36": {
   "revealed": false
  },
  "16,37": {
   "revealed": false
  },
  "16,38": {
   "revealed": false
  },
  "16,39": {
   "revealed": false
  },
  "16,40": {
   "revealed": false
  },
  "16,41": {
   "revealed": false
  },
  "16,42": {
   "revealed": false
  },
  "16,43": {
   "revealed": false
  },
  "16,44": {
   "revealed": false
  },
  "16,45": {
   "revealed": false
  },
  "16,46": {
   "revealed": false
  },
  "16,47": {
   "revealed": false
  },
  "16,48": {
   "revealed": false
  },
  "16,49": {
   "revealed": false
  },
  "17,0": {
   "revealed": false
  },
  "17,1": {
   "revealed": false
  },
  "17,2": {
   "revealed": false
  },
  "17,3": {
   "revealed": false
  },
  "17,4": {
   "revealed": false
  },
  "17,5": {
   "revealed": false
  },
  "17,6": {
   "revealed": false
  },
  "17,7": {
   "revealed": false
  },
  "17,8": {
   "revealed": false
  },
  "17,9": {
   "revealed": false
  },
  "17,10": {
   "revealed": false
  },
  "17,11": {
   "revealed": false
  },
  "17,12": {
   "revealed": false
  },
  "17,13": {
   "revealed": false
  },
  "17,14": {
   "revealed": false
  },
  "17,15": {
   "revealed": false
  },
  "17,16": {
   "revealed": false
  },
  "17,17": {
   "revealed": false
  },
  "17,18": {
   "revealed": false
  },
  "17,19": {
   "revealed": false
  },
  "17,20": {
   "revealed": false
  },
  "17,21": {
   "revealed": false
  },
  "17,22": {
   "revealed": false
  },
  "17,23": {
   "revealed": false
  },
  "17,24": {
   "revealed": false
  },
  "17,25": {
   "revealed": false
  },
  "17,26": {
   "revealed": false
  },
  "17,27": {
   "revealed": false
  },
  "17,28": {
   "revealed": false
  },
  "17,29": {
   "revealed": false
  },
  "17,30": {
   "revealed": false
  },
  "17,31": {
   "revealed": false
  },
  "17,32": {
   "revealed": false
  },
  "17,33": {
   "revealed": false
  },
  "17,34": {
   "revealed": false
  },
  "17,35": {
   "revealed": false
  },
  "17,36": {
   "revealed": false
  },
  "17,37": {
   "revealed": false
  },
  "17,38": {
   "revealed": false
  },
  "17,39": {
   "revealed": false
  },
  "17,40": {
   "revealed": false
  },
  "17,41": {
   "revealed": false
  },
  "17,42": {
   "revealed": false
  },
  "17,43": {
   "revealed": false
  },
  "17,44": {
   "revealed": false
  },
  "17,45": {
   "revealed": false
  },
  "17,46": {
   "revealed": false
  },
  "17,47": {
   "revealed": false
  },
  "17,48": {
   "revealed": false
  },
  "17,49": {
   "revealed": false
  },
  "18,0": {
   "revealed": false
  },
  "18,1": {
   "revealed": false
  },
  "18,2": {
   "revealed": false
  },
  "18,3": {
   "revealed": false
  },
  "18,4": {
   "revealed": false
  },
  "18,5": {
   "revealed": false
  },
  "18,6": {
   "revealed": false
  },
  "18,7": {
   "revealed": false
  },
  "18,8": {
   "revealed": false
  },
  "18,9": {
   "revealed": false
  },
  "18,10": {
   "revealed": false
  },
  "18,11": {
   "revealed": false
  },
  "18,12": {
   "revealed": false
  },
  "18,13": {
   "revealed": false
  },
  "18,14": {
   "revealed": false
  },
  "18,15": {
   "revealed": false
  },
  "18,16": {
   "revealed": false
  },
  "18,17": {
   "revealed": false
  },
  "18,18": {
   "revealed": false
  },
  "18,19": {
   "revealed": false
  },
  "18,20": {
   "revealed": false
  },
  "18,21": {
   "revealed": false
  },
  "18,22": {
   "revealed": false
  },
  "18,23": {
   "revealed": false
  },
  "18,24": {
   "revealed": false
  },
  "18,25": {
   "revealed": false
  },
  "18,26": {
   "revealed": false
  },
  "18,27": {
   "revealed": false
  },
  "18,28": {
   "revealed": false
  },
  "18,29": {
   "revealed": false
  },
  "18,30": {
   "revealed": false
  },
  "18,31": {
   "revealed": false
  },
  "18,32": {
   "revealed": false
  },
  "18,33": {
   "revealed": false
  },
  "18,34": {
   "revealed": false
  },
  "18,35": {
   "revealed": false
  },
  "18,36": {
   "revealed": false
  },
  "18,37": {
   "revealed": false
  },
  "18,38": {
   "revealed": false
  },
  "18,39": {
   "revealed": false
  },
  "18,40": {
   "revealed": false
  },
  "18,41": {
   "revealed": false
  },
  "18,42": {
   "revealed": false
  },
  "18,43": {
   "revealed": false
  },
  "18,44": {
   "revealed": false
  },
  "18,45": {
   "revealed": false
  },
  "18,46": {
   "revealed": false
  },
  "18,47": {
   "revealed": false
  },
  "18,48": {
   "revealed": false
  },
  "18,49": {
   "revealed": false
  },
  "19,0": {
   "revealed": false
  },
  "19,1": {
   "revealed": false
  },
  "19,2": {
   "revealed": false
  },
  "19,3": {
   "revealed": false
  },
  "19,4": {
   "revealed": false
  },
  "19,5": {
   "revealed": false
  },
  "19,6": {
   "revealed": false
  },
  "19,7": {
   "revealed": false
  },
  "19,8": {
   "revealed": false
  },
  "19,9": {
   "revealed": false
  },
  "19,10": {
   "revealed": false
  },
  "19,11": {
   "revealed": false
  },
  "19,12": {
   "revealed": false
  },
  "19,13": {
   "revealed": false
  },
  "19,14": {
   "revealed": false
  },
  "19,15": {
   "revealed": false
  },
  "19,16": {
   "revealed": false
  },
  "19,17": {
   "revealed": false
  },
  "19,18": {
   "revealed": false
  },
  "19,19": {
   "revealed": false
  },
  "19,20": {
   "revealed": false
  },
  "19,21": {
   "revealed": false
  },
  "19,22": {
   "revealed": false
  },
  "19,23": {
   "revealed": false
  },
  "19,24": {
   "revealed": false
  },
  "19,25": {
   "revealed": false
  },
  "19,26": {
   "revealed": false
  },
  "19,27": {
   "revealed": false
  },
  "19,28": {
   "revealed": false
  },
  "19,29": {
   "revealed": false
  },
  "19,30": {
   "revealed": false
  },
  "19,31": {
   "revealed": false
  },
  "19,32": {
   "revealed": false
  },
  "19,33": {
   "revealed": false
  },
  "19,34": {
   "revealed": false
  },
  "19,35": {
   "revealed": false
  },
  "19,36": {
   "revealed": false
  },
  "19,37": {
   "revealed": false
  },
  "19,38": {
   "revealed": false
  },
  "19,39": {
   "revealed": false
  },
  "19,40": {
   "revealed": false
  },
  "19,41": {
   "revealed": false
  },
  "19,42": {
   "revealed": false
  },
  "19,43": {
   "revealed": false
  },
  "19,44": {
   "revealed": false
  },
  "19,45": {
   "revealed": false
  },
  "19,46": {
   "revealed": false
  },
  "19,47": {
   "revealed": false
  },
  "19,48": {
   "revealed": false
  },
  "19,49": {
   "revealed": false
  },
  "20,0": {
   "revealed": false
  },
  "20,1": {
   "revealed": false
  },
  "20,2": {
   "revealed": false
  },
  "20,3": {
   "revealed": false
  },
  "20,4": {
   "revealed": false
  },
  "20,5": {
   "revealed": false
  },
  "20,6": {
   "revealed": false
  },
  "20,7": {
   "revealed": false
  },
  "20,8": {
   "revealed": false
  },
  "20,9": {
   "revealed": false
  },
  "20,10": {
   "revealed": false
  },
  "20,11": {
   "revealed": false
  },
  "20,12": {
   "revealed": false
  },
  "20,13": {
   "revealed": false
  },
  "20,14": {
   "revealed": false
  },
  "20,15": {
   "revealed": false
  },
  "20,16": {
   "revealed": false
  },
  "20,17": {
   "revealed": false
  },
  "20,18": {
   "revealed": false
  },
  "20,19": {
   "revealed": false
  },
  "20,20": {
   "revealed": false
  },
  "20,21": {
   "revealed": false
  },
  "20,22": {
   "revealed": false
  },
  "20,23": {
   "revealed": false
  },
  "20,24": {
   "revealed": false
  },
  "20,25": {
   "revealed": false
  },
  "20,26": {
   "revealed": false
  },
  "20,27": {
   "revealed": false
  },
  "20,28": {
   "revealed": false
  },
  "20,29": {
   "revealed": false
  },
  "20,30": {
   "revealed": false
  },
  "20,31": {
   "revealed": false
  },
  "20,32": {
   "revealed": false
  },
  "20,33": {
   "revealed": false
  },
  "20,34": {
   "revealed": false
  },
  "20,35": {
   "revealed": false
  },
  "20,36": {
   "revealed": false
  },
  "20,37": {
   "revealed": false
  },
  "20,38": {
   "revealed": false
  },
  "20,39": {
   "revealed": false
  },
  "20,40": {
   "revealed": false
  },
  "20,41": {
   "revealed": false
  },
  "20,42": {
   "revealed": false
  },
  "20,43": {
   "revealed": false
  },
  "20,44": {
   "revealed": false
  },
  "20,45": {
   "revealed": false
  },
  "20,46": {
   "revealed": false
  },
  "20,47": {
   "revealed": false
  },
  "20,48": {
   "revealed": false
  },
  "20,49": {
   "revealed": false
  },
  "21,0": {
   "revealed": false
  },
  "21,1": {
   "revealed": false
  },
  "21,2": {
   "revealed": false
  },
  "21,3": {
   "revealed": false
  },
  "21,4": {
   "revealed": false
  },
  "21,5": {
   "revealed": false
  },
  "21,6": {
   "revealed": false
  },
  "21,7": {
   "revealed": false
  },
  "21,8": {
   "revealed": false
  },
  "21,9": {
   "revealed": false
  },
  "21,10": {
   "revealed": false
  },
  "21,11": {
   "revealed": false
  },
  "21,12": {
   "revealed": false
  },
  "21,13": {
   "revealed": false
  },
  "21,14": {
   "revealed": false
  },
  "21,15": {
   "revealed": false
  },
  "21,16": {
   "revealed": false
  },
  "21,17": {
   "revealed": false
  },
  "21,18": {
   "revealed": false
  },
  "21,19": {
   "revealed": false
  },
  "21,20": {
   "revealed": false
  },
  "21,21": {
   "revealed": false
  },
  "21,22": {
   "revealed": false
  },
  "21,23": {
   "revealed": false
  },
  "21,24": {
   "revealed": false
  },
  "21,25": {
   "revealed": false
  },
  "21,26": {
   "revealed": false
  },
  "21,27": {
   "revealed": false
  },
  "21,28": {
   "revealed": false
  },
  "21,29": {
   "revealed": false
  },
  "21,30": {
   "revealed": false
  },
  "21,31": {
   "revealed": false
  },
  "21,32": {
   "revealed": false
  },
  "21,33": {
   "revealed": false
  },
  "21,34": {
   "revealed": false
  },
  "21,35": {
   "revealed": false
  },
  "21,36": {
   "revealed": false
  },
  "21,37": {
   "revealed": false
  },
  "21,38": {
   "revealed": false
  },
  "21,39": {
   "revealed": false
  },
  "21,40": {
   "revealed": false
  },
  "21,41": {
   "revealed": false
  },
  "21,42": {
   "revealed": false
  },
  "21,43": {
   "revealed": false
  },
  "21,44": {
   "revealed": false
  },
  "21,45": {
   "revealed": false
  },
  "21,46": {
   "revealed": false
  },
  "21,47": {
   "revealed": false
  },
  "21,48": {
   "revealed": false
  },
  "21,49": {
   "revealed": false
  },
  "22,0": {
   "revealed": false
  },
  "22,1": {
   "revealed": false
  },
  "22,2": {
   "revealed": false
  },
  "22,3": {
   "revealed": false
  },
  "22,4": {
   "revealed": false
  },
  "22,5": {
   "revealed": false
  },
  "22,6": {
   "revealed": false
  },
  "22,7": {
   "revealed": false
  },
  "22,8": {
   "revealed": false
  },
  "22,9": {
   "revealed": false
  },
  "22,10": {
   "revealed": false
  },
  "22,11": {
   "revealed": false
  },
  "22,12": {
   "revealed": false
  },
  "22,13": {
   "revealed": false
  },
  "22,14": {
   "revealed": false
  },
  "22,15": {
   "revealed": false
  },
  "22,16": {
   "revealed": false
  },
  "22,17": {
   "revealed": false
  },
  "22,18": {
   "revealed": false
  },
  "22,19": {
   "revealed": false
  },
  "22,20": {
   "revealed": false
  },
  "22,21": {
   "revealed": false
  },
  "22,22": {
   "revealed": false
  },
  "22,23": {
   "revealed": false
  },
  "22,24": {
   "revealed": false
  },
  "22,25": {
   "revealed": false
  },
  "22,26": {
   "revealed": false
  },
  "22,27": {
   "revealed": false
  },
  "22,28": {
   "revealed": false
  },
  "22,29": {
   "revealed": false
  },
  "22,30": {
   "revealed": false
  },
  "22,31": {
   "revealed": false
  },
  "22,32": {
   "revealed": false
  },
  "22,33": {
   "revealed": false
  },
  "22,34": {
   "revealed": false
  },
  "22,35": {
   "revealed": false
  },
  "22,36": {
   "revealed": false
  },
  "22,37": {
   "revealed": false
  },
  "22,38": {
   "revealed": false
  },
  "22,39": {
   "revealed": false
  },
  "22,40": {
   "revealed": false
  },
  "22,41": {
   "revealed": false
  },
  "22,42": {
   "revealed": false
  },
  "22,43": {
   "revealed": false
  },
  "22,44": {
   "revealed": false
  },
  "22,45": {
   "revealed": false
  },
  "22,46": {
   "revealed": false
  },
  "22,47": {
   "revealed": false
  },
  "22,48": {
   "revealed": false
  },
  "22,49": {
   "revealed": false
  },
  "23,0": {
   "revealed": false
  },
  "23,1": {
   "revealed": false
  },
  "23,2": {
   "revealed": false
  },
  "23,3": {
   "revealed": false
  },
  "23,4": {
   "revealed": false
  },
  "23,5": {
   "revealed": false
  },
  "23,6": {
   "revealed": false
  },
  "23,7": {
   "revealed": false
  },
  "23,8": {
   "revealed": false
  },
  "23,9": {
   "revealed": false
  },
  "23,10": {
   "revealed": false
  },
  "23,11": {
   "revealed": false
  },
  "23,12": {
   "revealed": false
  },
  "23,13": {
   "revealed": false
  },
  "23,14": {
   "revealed": false
  },
  "23,15": {
   "revealed": false
  },
  "23,16": {
   "revealed": false
  },
  "23,17": {
   "revealed": false
  },
  "23,18": {
   "revealed": false
  },
  "23,19": {
   "revealed": false
  },
  "23,20": {
   "revealed": false
  },
  "23,21": {
   "revealed": false
  },
  "23,22": {
   "revealed": false
  },
  "23,23": {
   "revealed": false
  },
  "23,24": {
   "revealed": false
  },
  "23,25": {
   "revealed": false
  },
  "23,26": {
   "revealed": false
  },
  "23,27": {
   "revealed": false
  },
  "23,28": {
   "revealed": false
  },
  "23,29": {
   "revealed": false
  },
  "23,30": {
   "revealed": false
  },
  "23,31": {
   "revealed": false
  },
  "23,32": {
   "revealed": false
  },
  "23,33": {
   "revealed": false
  },
  "23,34": {
   "revealed": false
  },
  "23,35": {
   "revealed": false
  },
  "23,36": {
   "revealed": false
  },
  "23,37": {
   "revealed": false
  },
  "23,38": {
   "revealed": false
  },
  "23,39": {
   "revealed": false
  },
  "23,40": {
   "revealed": false
  },
  "23,41": {
   "revealed": false
  },
  "23,42": {
   "revealed": false
  },
  "23,43": {
   "revealed": false
  },
  "23,44": {
   "revealed": false
  },
  "23,45": {
   "revealed": false
  },
  "23,46": {
   "revealed": false
  },
  "23,47": {
   "revealed": false
  },
  "23,48": {
   "revealed": false
  },
  "23,49": {
   "revealed": false
  },
  "24,0": {
   "revealed": false
  },
  "24,1": {
   "revealed": false
  },
  "24,2": {
   "revealed": false
  },
  "24,3": {
   "revealed": false
  },
  "24,4": {
   "revealed": false
  },
  "24,5": {
   "revealed": false
  },
  "24,6": {
   "revealed": false
  },
  "24,7": {
   "revealed": false
  },
  "24,8": {
   "revealed": false
  },
  "24,9": {
   "revealed": false
  },
  "24,10": {
   "revealed": false
  },
  "24,11": {
   "revealed": false
  },
  "24,12": {
   "revealed": false
  },
  "24,13": {
   "revealed": false
  },
  "24,14": {
   "revealed": false
  },
  "24,15": {
   "revealed": false
  },
  "24,16": {
   "revealed": false
  },
  "24,17": {
   "revealed": false
  },
  "24,18": {
   "revealed": false
  },
  "24,19": {
   "revealed": false
  },
  "24,20": {
   "revealed": false
  },
  "24,21": {
   "revealed": false
  },
  "24,22": {
   "revealed": false
  },
  "24,23": {
   "revealed": false
  },
  "24,24": {
   "revealed": false
  },
  "24,25": {
   "revealed": false
  },
  "24,26": {
   "revealed": false
  },
  "24,27": {
   "revealed": false
  },
  "24,28": {
   "revealed": false
  },
  "24,29": {
   "revealed": false
  },
  "24,30": {
   "revealed": false
  },
  "24,31": {
   "revealed": false
  },
  "24,32": {
   "revealed": false
  },
  "24,33": {
   "revealed": false
  },
  "24,34": {
   "revealed": false
  },
  "24,35": {
   "revealed": false
  },
  "24,36": {
   "revealed": false
  },
  "24,37": {
   "revealed": false
  },
  "24,38": {
   "revealed": false
  },
  "24,39": {
   "revealed": false
  },
  "24,40": {
   "revealed": false
  },
  "24,41": {
   "revealed": false
  },
  "24,42": {
   "revealed": false
  },
  "24,43": {
   "revealed": false
  },
  "24,44": {
   "revealed": false
  },
  "24,45": {
   "revealed": false
  },
  "24,46": {
   "revealed": false
  },
  "24,47": {
   "revealed": false
  },
  "24,48": {
   "revealed": false
  },
  "24,49": {
   "revealed": false
  },
  "25,0": {
   "revealed": false
  },
  "25,1": {
   "revealed": false
  },
  "25,2": {
   "revealed": false
  },
  "25,3": {
   "revealed": false
  },
  "25,4": {
   "revealed": false
  },
  "25,5": {
   "revealed": false
  },
  "25,6": {
   "revealed": false
  },
  "25,7": {
   "revealed": false
  },
  "25,8": {
   "revealed": false
  },
  "25,9": {
   "revealed": false
  },
  "25,10": {
   "revealed": false
  },
  "25,11": {
   "revealed": false
  },
  "25,12": {
   "revealed": false
  },
  "25,13": {
   "revealed": false
  },
  "25,14": {
   "revealed": false
  },
  "25,15": {
   "revealed": false
  },
  "25,16": {
   "revealed": false
  },
  "25,17": {
   "revealed": false
  },
  "25,18": {
   "revealed": false
  },
  "25,19": {
   "revealed": false
  },
  "25,20": {
   "revealed": false
  },
  "25,21": {
   "revealed": false
  },
  "25,22": {
   "revealed": false
  },
  "25,23": {
   "revealed": false
  },
  "25,24": {
   "revealed": false
  },
  "25,25": {
   "revealed": false
  },
  "25,26": {
   "revealed": false
  },
  "25,27": {
   "revealed": false
  },
  "25,28": {
   "revealed": false
  },
  "25,29": {
   "revealed": false
  },
  "25,30": {
   "revealed": false
  },
  "25,31": {
   "revealed": false
  },
  "25,32": {
   "revealed": false
  },
  "25,33": {
   "revealed": false
  },
  "25,34": {
   "revealed": false
  },
  "25,35": {
   "revealed": false
  },
  "25,36": {
   "revealed": false
  },
  "25,37": {
   "revealed": false
  },
  "25,38": {
   "revealed": false
  },
  "25,39": {
   "revealed": false
  },
  "25,40": {
   "revealed": false
  },
  "25,41": {
   "revealed": false
  },
  "25,42": {
   "revealed": false
  },
  "25,43": {
   "revealed": false
  },
  "25,44": {
   "revealed": false
  },
  "25,45": {
   "revealed": false
  },
  "25,46": {
   "revealed": false
  },
  "25,47": {
   "revealed": false
  },
  "25,48": {
   "revealed": false
  },
  "25,49": {
   "revealed": false
  },
  "26,0": {
   "revealed": false
  },
  "26,1": {
   "revealed": false
  },
  "26,2": {
   "revealed": false
  },
  "26,3": {
   "revealed": false
  },
  "26,4": {
   "revealed": false
  },
  "26,5": {
   "revealed": false
  },
  "26,6": {
   "revealed": false
  },
  "26,7": {
   "revealed": false
  },
  "26,8": {
   "revealed": false
  },
  "26,9": {
   "revealed": false
  },
  "26,10": {
   "revealed": false
  },
  "26,11": {
   "revealed": false
  },
  "26,12": {
   "revealed": false
  },
  "26,13": {
   "revealed": false
  },
  "26,14": {
   "revealed": false
  },
  "26,15": {
   "revealed": false
  },
  "26,16": {
   "revealed": false
  },
  "26,17": {
   "revealed": false
  },
  "26,18": {
   "revealed": false
  },
  "26,19": {
   "revealed": false
  },
  "26,20": {
   "revealed": false
  },
  "26,21": {
   "revealed": false
  },
  "26,22": {
   "revealed": false
  },
  "26,23": {
   "revealed": false
  },
  "26,24": {
   "revealed": false
  },
  "26,25": {
   "revealed": false
  },
  "26,26": {
   "revealed": false
  },
  "26,27": {
   "revealed": false
  },
  "26,28": {
   "revealed": false
  },
  "26,29": {
   "revealed": false
  },
  "26,30": {
   "revealed": false
  },
  "26,31": {
   "revealed": false
  },
  "26,32": {
   "revealed": false
  },
  "26,33": {
   "revealed": false
  },
  "26,34": {
   "revealed": false
  },
  "26,35": {
   "revealed": false
  },
  "26,36": {
   "revealed": false
  },
  "26,37": {
   "revealed": false
  },
  "26,38": {
   "revealed": false
  },
  "26,39": {
   "revealed": false
  },
  "26,40": {
   "revealed": false
  },
  "26,41": {
   "revealed": false
  },
  "26,42": {
   "revealed": false
  },
  "26,43": {
   "revealed": false
  },
  "26,44": {
   "revealed": false
  },
  "26,45": {
   "revealed": false
  },
  "26,46": {
   "revealed": false
  },
  "26,47": {
   "revealed": false
  },
  "26,48": {
   "revealed": false
  },
  "26,49": {
   "revealed": false
  },
  "27,0": {
   "revealed": false
  },
  "27,1": {
   "revealed": false
  },
  "27,2": {
   "revealed": false
  },
  "27,3": {
   "revealed": false
  },
  "27,4": {
   "revealed": false
  },
  "27,5": {
   "revealed": false
  },
  "27,6": {
   "revealed": false
  },
  "27,7": {
   "revealed": false
  },
  "27,8": {
   "revealed": false
  },
  "27,9": {
   "revealed": false
  },
  "27,10": {
   "revealed": false
  },
  "27,11": {
   "revealed": false
  },
  "27,12": {
   "revealed": false
  },
  "27,13": {
   "revealed": false
  },
  "27,14": {
   "revealed": false
  },
  "27,15": {
   "revealed": false
  },
  "27,16": {
   "revealed": false
  },
  "27,17": {
   "revealed": false
  },
  "27,18": {
   "revealed": false
  },
  "27,19": {
   "revealed": false
  },
  "27,20": {
   "revealed": false
  },
  "27,21": {
   "revealed": false
  },
  "27,22": {
   "revealed": false
  },
  "27,23": {
   "revealed": false
  },
  "27,24": {
   "revealed": false
  },
  "27,25": {
   "revealed": false
  },
  "27,26": {
   "revealed": false
  },
  "27,27": {
   "revealed": false
  },
  "27,28": {
   "revealed": false
  },
  "27,29": {
   "revealed": false
  },
  "27,30": {
   "revealed": false
  },
  "27,31": {
   "revealed": false
  },
  "27,32": {
   "revealed": false
  },
  "27,33": {
   "revealed": false
  },
  "27,34": {
   "revealed": false
  },
  "27,35": {
   "revealed": false
  },
  "27,36": {
   "revealed": false
  },
  "27,37": {
   "revealed": false
  },
  "27,38": {
   "revealed": false
  },
  "27,39": {
   "revealed": false
  },
  "27,40": {
   "revealed": false
  },
  "27,41": {
   "revealed": false
  },
  "27,42": {
   "revealed": false
  },
  "27,43": {
   "revealed": false
  },
  "27,44": {
   "revealed": false
  },
  "27,45": {
   "revealed": false
  },
  "27,46": {
   "revealed": false
  },
  "27,47": {
   "revealed": false
  },
  "27,48": {
   "revealed": false
  },
  "27,49": {
   "revealed": false
  },
  "28,0": {
   "revealed": false
  },
  "28,1": {
   "revealed": false
  },
  "28,2": {
   "revealed": false
  },
  "28,3": {
   "revealed": false
  },
  "28,4": {
   "revealed": false
  },
  "28,5": {
   "revealed": false
  },
  "28,6": {
   "revealed": false
  },
  "28,7": {
   "revealed": false
  },
  "28,8": {
   "revealed": false
  },
  "28,9": {
   "revealed": false
  },
  "28,10": {
   "revealed": false
  },
  "28,11": {
   "revealed": false
  },
  "28,12": {
   "revealed": false
  },
  "28,13": {
   "revealed": false
  },
  "28,14": {
   "revealed": false
  },
  "28,15": {
   "revealed": false
  },
  "28,16": {
   "revealed": false
  },
  "28,17": {
   "revealed": false
  },
  "28,18": {
   "revealed": false
  },
  "28,19": {
   "revealed": false
  },
  "28,20": {
   "revealed": false
  },
  "28,21": {
   "revealed": false
  },
  "28,22": {
   "revealed": false
  },
  "28,23": {
   "revealed": false
  },
  "28,24": {
   "revealed": false
  },
  "28,25": {
   "revealed": false
  },
  "28,26": {
   "revealed": false
  },
  "28,27": {
   "revealed": false
  },
  "28,28": {
   "revealed": false
  },
  "28,29": {
   "revealed": false
  },
  "28,30": {
   "revealed": false
  },
  "28,31": {
   "revealed": false
  },
  "28,32": {
   "revealed": false
  },
  "28,33": {
   "revealed": false
  },
  "28,34": {
   "revealed": false
  },
  "28,35": {
   "revealed": false
  },
  "28,36": {
   "revealed": false
  },
  "28,37": {
   "revealed": false
  },
  "28,38": {
   "revealed": false
  },
  "28,39": {
   "revealed": false
  },
  "28,40": {
   "revealed": false
  },
  "28,41": {
   "revealed": false
  },
  "28,42": {
   "revealed": false
  },
  "28,43": {
   "revealed": false
  },
  "28,44": {
   "revealed": false
  },
  "28,45": {
   "revealed": false
  },
  "28,46": {
   "revealed": false
  },
  "28,47": {
   "revealed": false
  },
  "28,48": {
   "revealed": false
  },
  "28,49": {
   "revealed": false
  },
  "29,0": {
   "revealed": false
  },
  "29,1": {
   "revealed": false
  },
  "29,2": {
   "revealed": false
  },
  "29,3": {
   "revealed": false
  },
  "29,4": {
   "revealed": false
  },
  "29,5": {
   "revealed": false
  },
  "29,6": {
   "revealed": false
  },
  "29,7": {
   "revealed": false
  },
  "29,8": {
   "revealed": false
  },
  "29,9": {
   "revealed": false
  },
  "29,10": {
   "revealed": false
  },
  "29,11": {
   "revealed": false
  },
  "29,12": {
   "revealed": false
  },
  "29,13": {
   "revealed": false
  },
  "29,14": {
   "revealed": false
  },
  "29,15": {
   "revealed": false
  },
  "29,16": {
   "revealed": false
  },
  "29,17": {
   "revealed": false
  },
  "29,18": {
   "revealed": false
  },
  "29,19": {
   "revealed": false
  },
  "29,20": {
   "revealed": false
  },
  "29,21": {
   "revealed": false
  },
  "29,22": {
   "revealed": false
  },
  "29,23": {
   "revealed": false
  },
  "29,24": {
   "revealed": false
  },
  "29,25": {
   "revealed": false
  },
  "29,26": {
   "revealed": false
  },
  "29,27": {
   "revealed": false
  },
  "29,28": {
   "revealed": false
  },
  "29,29": {
   "revealed": false
  },
  "29,30": {
   "revealed": false
  },
  "29,31": {
   "revealed": false
  },
  "29,32": {
   "revealed": false
  },
  "29,33": {
   "revealed": false
  },
  "29,34": {
   "revealed": false
  },
  "29,35": {
   "revealed": false
  },
  "29,36": {
   "revealed": false
  },
  "29,37": {
   "revealed": false
  },
  "29,38": {
   "revealed": false
  },
  "29,39": {
   "revealed": false
  },
  "29,40": {
   "revealed": false
  },
  "29,41": {
   "revealed": false
  },
  "29,42": {
   "revealed": false
  },
  "29,43": {
   "revealed": false
  },
  "29,44": {
   "revealed": false
  },
  "29,45": {
   "revealed": false
  },
  "29,46": {
   "revealed": false
  },
  "29,47": {
   "revealed": false
  },
  "29,48": {
   "revealed": false
  },
  "29,49": {
   "revealed": false
  },
  "30,0": {
   "revealed": false
  },
  "30,1": {
   "revealed": false
  },
  "30,2": {
   "revealed": false
  },
  "30,3": {
   "revealed": false
  },
  "30,4": {
   "revealed": false
  },
  "30,5": {
   "revealed": false
  },
  "30,6": {
   "revealed": false
  },
  "30,7": {
   "revealed": false
  },
  "30,8": {
   "revealed": false
  },
  "30,9": {
   "revealed": false
  },
  "30,10": {
   "revealed": false
  },
  "30,11": {
   "revealed": false
  },
  "30,12": {
   "revealed": false
  },
  "30,13": {
   "revealed": false
  },
  "30,14": {
   "revealed": false
  },
  "30,15": {
   "revealed": false
  },
  "30,16": {
   "revealed": false
  },
  "30,17": {
   "revealed": false
  },
  "30,18": {
   "revealed": false
  },
  "30,19": {
   "revealed": false
  },
  "30,20": {
   "revealed": false
  },
  "30,21": {
   "revealed": false
  },
  "30,22": {
   "revealed": false
  },
  "30,23": {
   "revealed": false
  },
  "30,24": {
   "revealed": false
  },
  "30,25": {
   "revealed": false
  },
  "30,26": {
   "revealed": false
  },
  "30,27": {
   "revealed": false
  },
  "30,28": {
   "revealed": false
  },
  "30,29": {
   "revealed": false
  },
  "30,30": {
   "revealed": false
  },
  "30,31": {
   "revealed": false
  },
  "30,32": {
   "revealed": false
  },
  "30,33": {
   "revealed": false
  },
  "30,34": {
   "revealed": false
  },
  "30,35": {
   "revealed": false
  },
  "30,36": {
   "revealed": false
  },
  "30,37": {
   "revealed": false
  },
  "30,38": {
   "revealed": false
  },
  "30,39": {
   "revealed": false
  },
  "30,40": {
   "revealed": false
  },
  "30,41": {
   "revealed": false
  },
  "30,42": {
   "revealed": false
  },
  "30,43": {
   "revealed": false
  },
  "30,44": {
   "revealed": false
  },
  "30,45": {
   "revealed": false
  },
  "30,46": {
   "revealed": false
  },
  "30,47": {
   "revealed": false
  },
  "30,48": {
   "revealed": false
  },
  "30,49": {
   "revealed": false
  },
  "31,0": {
   "revealed": false
  },
  "31,1": {
   "revealed": false
  },
  "31,2": {
   "revealed": false
  },
  "31,3": {
   "revealed": false
  },
  "31,4": {
   "revealed": false
  },
  "31,5": {
   "revealed": false
  },
  "31,6": {
   "revealed": false
  },
  "31,7": {
   "revealed": false
  },
  "31,8": {
   "revealed": false
  },
  "31,9": {
   "revealed": false
  },
  "31,10": {
   "revealed": false
  },
  "31,11": {
   "revealed": false
  },
  "31,12": {
   "revealed": false
  },
  "31,13": {
   "revealed": false
  },
  "31,14": {
   "revealed": false
  },
  "31,15": {
   "revealed": false
  },
  "31,16": {
   "revealed": false
  },
  "31,17": {
   "revealed": false
  },
  "31,18": {
   "revealed": false
  },
  "31,19": {
   "revealed": false
  },
  "31,20": {
   "revealed": false
  },
  "31,21": {
   "revealed": false
  },
  "31,22": {
   "revealed": false
  },
  "31,23": {
   "revealed": false
  },
  "31,24": {
   "revealed": false
  },
  "31,25": {
   "revealed": false
  },
  "31,26": {
   "revealed": false
  },
  "31,27": {
   "revealed": false
  },
  "31,28": {
   "revealed": false
  },
  "31,29": {
   "revealed": false
  },
  "31,30": {
   "revealed": false
  },
  "31,31": {
   "revealed": false
  },
  "31,32": {
   "revealed": false
  },
  "31,33": {
   "revealed": false
  },
  "31,34": {
   "revealed": false
  },
  "31,35": {
   "revealed": false
  },
  "31,36": {
   "revealed": false
  },
  "31,37": {
   "revealed": false
  },
  "31,38": {
   "revealed": false
  },
  "31,39": {
   "revealed": false
  },
  "31,40": {
   "revealed": false
  },
  "31,41": {
   "revealed": false
  },
  "31,42": {
   "revealed": false
  },
  "31,43": {
   "revealed": false
  },
  "31,44": {
   "revealed": false
  },
  "31,45": {
   "revealed": false
  },
  "31,46": {
   "revealed": false
  },
  "31,47": {
   "revealed": false
  },
  "31,48": {
   "revealed": false
  },
  "31,49": {
   "revealed": false
  },
  "32,0": {
   "revealed": false
  },
  "32,1": {
   "revealed": false
  },
  "32,2": {
   "revealed": false
  },
  "32,3": {
   "revealed": false
  },
  "32,4": {
   "revealed": false
  },
  "32,5": {
   "revealed": false
  },
  "32,6": {
   "revealed": false
  },
  "32,7": {
   "revealed": false
  },
  "32,8": {
   "revealed": false
  },
  "32,9": {
   "revealed": false
  },
  "32,10": {
   "revealed": false
  },
  "32,11": {
   "revealed": false
  },
  "32,12": {
   "revealed": false
  },
  "32,13": {
   "revealed": false
  },
  "32,14": {
   "revealed": false
  },
  "32,15": {
   "revealed": false
  },
  "32,16": {
   "revealed": false
  },
  "32,17": {
   "revealed": false
  },
  "32,18": {
   "revealed": false
  },
  "32,19": {
   "revealed": false
  },
  "32,20": {
   "revealed": false
  },
  "32,21": {
   "revealed": false
  },
  "32,22": {
   "revealed": false
  },
  "32,23": {
   "revealed": false
  },
  "32,24": {
   "revealed": false
  },
  "32,25": {
   "revealed": false
  },
  "32,26": {
   "revealed": false
  },
  "32,27": {
   "revealed": false
  },
  "32,28": {
   "revealed": false
  },
  "32,29": {
   "revealed": false
  },
  "32,30": {
   "revealed": false
  },
  "32,31": {
   "revealed": false
  },
  "32,32": {
   "revealed": false
  },
  "32,33": {
   "revealed": false
  },
  "32,34": {
   "revealed": false
  },
  "32,35": {
   "revealed": false
  },
  "32,36": {
   "revealed": false
  },
  "32,37": {
   "revealed": false
  },
  "32,38": {
   "revealed": false
  },
  "32,39": {
   "revealed": false
  },
  "32,40": {
   "revealed": false
  },
  "32,41": {
   "revealed": false
  },
  "32,42": {
   "revealed": false
  },
  "32,43": {
   "revealed": false
  },
  "32,44": {
   "revealed": false
  },
  "32,45": {
   "revealed": false
  },
  "32,46": {
   "revealed": false
  },
  "32,47": {
   "revealed": false
  },
  "32,48": {
   "revealed": false
  },
  "32,49": {
   "revealed": false
  },
  "33,0": {
   "revealed": false
  },
  "33,1": {
   "revealed": false
  },
  "33,2": {
   "revealed": false
  },
  "33,3": {
   "revealed": false
  },
  "33,4": {
   "revealed": false
  },
  "33,5": {
   "revealed": false
  },
  "33,6": {
   "revealed": false
  },
  "33,7": {
   "revealed": false
  },
  "33,8": {
   "revealed": false
  },
  "33,9": {
   "revealed": false
  },
  "33,10": {
   "revealed": false
  },
  "33,11": {
   "revealed": false
  },
  "33,12": {
   "revealed": false
  },
  "33,13": {
   "revealed": false
  },
  "33,14": {
   "revealed": false
  },
  "33,15": {
   "revealed": false
  },
  "33,16": {
   "revealed": false
  },
  "33,17": {
   "revealed": false
  },
  "33,18": {
   "revealed": false
  },
  "33,19": {
   "revealed": false
  },
  "33,20": {
   "revealed": false
  },
  "33,21": {
   "revealed": false
  },
  "33,22": {
   "revealed": false
  },
  "33,23": {
   "revealed": false
  },
  "33,24": {
   "revealed": false
  },
  "33,25": {
   "revealed": false
  },
  "33,26": {
   "revealed": false
  },
  "33,27": {
   "revealed": false
  },
  "33,28": {
   "revealed": false
  },
  "33,29": {
   "revealed": false
  },
  "33,30": {
   "revealed": false
  },
  "33,31": {
   "revealed": false
  },
  "33,32": {
   "revealed": false
  },
  "33,33": {
   "revealed": false
  },
  "33,34": {
   "revealed": false
  },
  "33,35": {
   "revealed": false
  },
  "33,36": {
   "revealed": false
  },
  "33,37": {
   "revealed": false
  },
  "33,38": {
   "revealed": false
  },
  "33,39": {
   "revealed": false
  },
  "33,40": {
   "revealed": false
  },
  "33,41": {
   "revealed": false
  },
  "33,42": {
   "revealed": false
  },
  "33,43": {
   "revealed": false
  },
  "33,44": {
   "revealed": false
  },
  "33,45": {
   "revealed": false
  },
  "33,46": {
   "revealed": false
  },
  "33,47": {
   "revealed": false
  },
  "33,48": {
   "revealed": false
  },
  "33,49": {
   "revealed": false
  },
  "34,0": {
   "revealed": false
  },
  "34,1": {
   "revealed": false
  },
  "34,2": {
   "revealed": false
  },
  "34,3": {
   "revealed": false
  },
  "34,4": {
   "revealed": false
  },
  "34,5": {
   "revealed": false
  },
  "34,6": {
   "revealed": false
  },
  "34,7": {
   "revealed": false
  },
  "34,8": {
   "revealed": false
  },
  "34,9": {
   "revealed": false
  },
  "34,10": {
   "revealed": false
  },
  "34,11": {
   "revealed": false
  },
  "34,12": {
   "revealed": false
  },
  "34,13": {
   "revealed": false
  },
  "34,14": {
   "revealed": false
  },
  "34,15": {
   "revealed": false
  },
  "34,16": {
   "revealed": false
  },
  "34,17": {
   "revealed": false
  },
  "34,18": {
   "revealed": false
  },
  "34,19": {
   "revealed": false
  },
  "34,20": {
   "revealed": false
  },
  "34,21": {
   "revealed": false
  },
  "34,22": {
   "revealed": false
  },
  "34,23": {
   "revealed": false
  },
  "34,24": {
   "revealed": false
  },
  "34,25": {
   "revealed": false
  },
  "34,26": {
   "revealed": false
  },
  "34,27": {
   "revealed": false
  },
  "34,28": {
   "revealed": false
  },
  "34,29": {
   "revealed": false
  },
  "34,30": {
   "revealed": false
  },
  "34,31": {
   "revealed": false
  },
  "34,32": {
   "revealed": false
  },
  "34,33": {
   "revealed": false
  },
  "34,34": {
   "revealed": false
  },
  "34,35": {
   "revealed": false
  },
  "34,36": {
   "revealed": false
  },
  "34,37": {
   "revealed": false
  },
  "34,38": {
   "revealed": false
  },
  "34,39": {
   "revealed": false
  },
  "34,40": {
   "revealed": false
  },
  "34,41": {
   "revealed": false
  },
  "34,42": {
   "revealed": false
  },
  "34,43": {
   "revealed": false
  },
  "34,44": {
   "revealed": false
  },
  "34,45": {
   "revealed": false
  },
  "34,46": {
   "revealed": false
  },
  "34,47": {
   "revealed": false
  },
  "34,48": {
   "revealed": false
  },
  "34,49": {
   "revealed": false
  },
  "35,0": {
   "revealed": false
  },
  "35,1": {
   "revealed": false
  },
  "35,2": {
   "revealed": false
  },
  "35,3": {
   "revealed": false
  },
  "35,4": {
   "revealed": false
  },
  "35,5": {
   "revealed": false
  },
  "35,6": {
   "revealed": false
  },
  "35,7": {
   "revealed": false
  },
  "35,8": {
   "revealed": false
  },
  "35,9": {
   "revealed": false
  },
  "35,10": {
   "revealed": false
  },
  "35,11": {
   "revealed": false
  },
  "35,12": {
   "revealed": false
  },
  "35,13": {
   "revealed": false
  },
  "35,14": {
   "revealed": false
  },
  "35,15": {
   "revealed": false
  },
  "35,16": {
   "revealed": false
  },
  "35,17": {
   "revealed": false
  },
  "35,18": {
   "revealed": false
  },
  "35,19": {
   "revealed": false
  },
  "35,20": {
   "revealed": false
  },
  "35,21": {
   "revealed": false
  },
  "35,22": {
   "revealed": false
  },
  "35,23": {
   "revealed": false
  },
  "35,24": {
   "revealed": false
  },
  "35,25": {
   "revealed": false
  },
  "35,26": {
   "revealed": false
  },
  "35,27": {
   "revealed": false
  },
  "35,28": {
   "revealed": false
  },
  "35,29": {
   "revealed": false
  },
  "35,30": {
   "revealed": false
  },
  "35,31": {
   "revealed": false
  },
  "35,32": {
   "revealed": false
  },
  "35,33": {
   "revealed": false
  },
  "35,34": {
   "revealed": false
  },
  "35,35": {
   "revealed": false
  },
  "35,36": {
   "revealed": false
  },
  "35,37": {
   "revealed": false
  },
  "35,38": {
   "revealed": false
  },
  "35,39": {
   "revealed": false
  },
  "35,40": {
   "revealed": false
  },
  "35,41": {
   "revealed": false
  },
  "35,42": {
   "revealed": false
  },
  "35,43": {
   "revealed": false
  },
  "35,44": {
   "revealed": false
  },
  "35,45": {
   "revealed": false
  },
  "35,46": {
   "revealed": false
  },
  "35,47": {
   "revealed": false
  },
  "35,48": {
   "revealed": false
  },
  "35,49": {
   "revealed": false
  },
  "36,0": {
   "revealed": false
  },
  "36,1": {
   "revealed": false
  },
  "36,2": {
   "revealed": false
  },
  "36,3": {
   "revealed": false
  },
  "36,4": {
   "revealed": false
  },
  "36,5": {
   "revealed": false
  },
  "36,6": {
   "revealed": false
  },
  "36,7": {
   "revealed": false
  },
  "36,8": {
   "revealed": false
  },
  "36,9": {
   "revealed": false
  },
  "36,10": {
   "revealed": false
  },
  "36,11": {
   "revealed": false
  },
  "36,12": {
   "revealed": false
  },
  "36,13": {
   "revealed": false
  },
  "36,14": {
   "revealed": false
  },
  "36,15": {
   "revealed": false
  },
  "36,16": {
   "revealed": false
  },
  "36,17": {
   "revealed": false
  },
  "36,18": {
   "revealed": false
  },
  "36,19": {
   "revealed": false
  },
  "36,20": {
   "revealed": false
  },
  "36,21": {
   "revealed": false
  },
  "36,22": {
   "revealed": false
  },
  "36,23": {
   "revealed": false
  },
  "36,24": {
   "revealed": false
  },
  "36,25": {
   "revealed": false
  },
  "36,26": {
   "revealed": false
  },
  "36,27": {
   "revealed": false
  },
  "36,28": {
   "revealed": false
  },
  "36,29": {
   "revealed": false
  },
  "36,30": {
   "revealed": false
  },
  "36,31": {
   "revealed": false
  },
  "36,32": {
   "revealed": false
  },
  "36,33": {
   "revealed": false
  },
  "36,34": {
   "revealed": false
  },
  "36,35": {
   "revealed": false
  },
  "36,36": {
   "revealed": false
  },
  "36,37": {
   "revealed": false
  },
  "36,38": {
   "revealed": false
  },
  "36,39": {
   "revealed": false
  },
  "36,40": {
   "revealed": false
  },
  "36,41": {
   "revealed": false
  },
  "36,42": {
   "revealed": false
  },
  "36,43": {
   "revealed": false
  },
  "36,44": {
   "revealed": false
  },
  "36,45": {
   "revealed": false
  },
  "36,46": {
   "revealed": false
  },
  "36,47": {
   "revealed": false
  },
  "36,48": {
   "revealed": false
  },
  "36,49": {
   "revealed": false
  },
  "37,0": {
   "revealed": false
  },
  "37,1": {
   "revealed": false
  },
  "37,2": {
   "revealed": false
  },
  "37,3": {
   "revealed": false
  },
  "37,4": {
   "revealed": false
  },
  "37,5": {
   "revealed": false
  },
  "37,6": {
   "revealed": false
  },
  "37,7": {
   "revealed": false
  },
  "37,8": {
   "revealed": false
  },
  "37,9": {
   "revealed": false
  },
  "37,10": {
   "revealed": false
  },
  "37,11": {
   "revealed": false
  },
  "37,12": {
   "revealed": false
  },
  "37,13": {
   "revealed": false
  },
  "37,14": {
   "revealed": false
  },
  "37,15": {
   "revealed": false
  },
  "37,16": {
   "revealed": false
  },
  "37,17": {
   "revealed": false
  },
  "37,18": {
   "revealed": false
  },
  "37,19": {
   "revealed": false
  },
  "37,20": {
   "revealed": false
  },
  "37,21": {
   "revealed": false
  },
  "37,22": {
   "revealed": false
  },
  "37,23": {
   "revealed": false
  },
  "37,24": {
   "revealed": false
  },
  "37,25": {
   "revealed": false
  },
  "37,26": {
   "revealed": false
  },
  "37,27": {
   "revealed": false
  },
  "37,28": {
   "revealed": false
  },
  "37,29": {
   "revealed": false
  },
  "37,30": {
   "revealed": false
  },
  "37,31": {
   "revealed": false
  },
  "37,32": {
   "revealed": false
  },
  "37,33": {
   "revealed": false
  },
  "37,34": {
   "revealed": false
  },
  "37,35": {
   "revealed": false
  },
  "37,36": {
   "revealed": false
  },
  "37,37": {
   "revealed": false
  },
  "37,38": {
   "revealed": false
  },
  "37,39": {
   "revealed": false
  },
  "37,40": {
   "revealed": false
  },
  "37,41": {
   "revealed": false
  },
  "37,42": {
   "revealed": false
  },
  "37,43": {
   "revealed": false
  },
  "37,44": {
   "revealed": false
  },
  "37,45": {
   "revealed": false
  },
  "37,46": {
   "revealed": false
  },
  "37,47": {
   "revealed": false
  },
  "37,48": {
   "revealed": false
  },
  "37,49": {
   "revealed": false
  },
  "38,0": {
   "revealed": false
  },
  "38,1": {
   "revealed": false
  },
  "38,2": {
   "revealed": false
  },
  "38,3": {
   "revealed": false
  },
  "38,4": {
   "revealed": false
  },
  "38,5": {
   "revealed": false
  },
  "38,6": {
   "revealed": false
  },
  "38,7": {
   "revealed": false
  },
  "38,8": {
   "revealed": false
  },
  "38,9": {
   "revealed": false
  },
  "38,10": {
   "revealed": false
  },
  "38,11": {
   "revealed": false
  },
  "38,12": {
   "revealed": false
  },
  "38,13": {
   "revealed": false
  },
  "38,14": {
   "revealed": false
  },
  "38,15": {
   "revealed": false
  },
  "38,16": {
   "revealed": false
  },
  "38,17": {
   "revealed": false
  },
  "38,18": {
   "revealed": false
  },
  "38,19": {
   "revealed": false
  },
  "38,20": {
   "revealed": false
  },
  "38,21": {
   "revealed": false
  },
  "38,22": {
   "revealed": false
  },
  "38,23": {
   "revealed": false
  },
  "38,24": {
   "revealed": false
  },
  "38,25": {
   "revealed": false
  },
  "38,26": {
   "revealed": false
  },
  "38,27": {
   "revealed": false
  },
  "38,28": {
   "revealed": false
  },
  "38,29": {
   "revealed": false
  },
  "38,30": {
   "revealed": false
  },
  "38,31": {
   "revealed": false
  },
  "38,32": {
   "revealed": false
  },
  "38,33": {
   "revealed": false
  },
  "38,34": {
   "revealed": false
  },
  "38,35": {
   "revealed": false
  },
  "38,36": {
   "revealed": false
  },
  "38,37": {
   "revealed": false
  },
  "38,38": {
   "revealed": false
  },
  "38,39": {
   "revealed": false
  },
  "38,40": {
   "revealed": false
  },
  "38,41": {
   "revealed": false
  },
  "38,42": {
   "revealed": false
  },
  "38,43": {
   "revealed": false
  },
  "38,44": {
   "revealed": false
  },
  "38,45": {
   "revealed": false
  },
  "38,46": {
   "revealed": false
  },
  "38,47": {
   "revealed": false
  },
  "38,48": {
   "revealed": false
  },
  "38,49": {
   "revealed": false
  },
  "39,0": {
   "revealed": false
  },
  "39,1": {
   "revealed": false
  },
  "39,2": {
   "revealed": false
  },
  "39,3": {
   "revealed": false
  },
  "39,4": {
   "revealed": false
  },
  "39,5": {
   "revealed": false
  },
  "39,6": {
   "revealed": false
  },
  "39,7": {
   "revealed": false
  },
  "39,8": {
   "revealed": false
  },
  "39,9": {
   "revealed": false
  },
  "39,10": {
   "revealed": false
  },
  "39,11": {
   "revealed": false
  },
  "39,12": {
   "revealed": false
  },
  "39,13": {
   "revealed": false
  },
  "39,14": {
   "revealed": false
  },
  "39,15": {
   "revealed": false
  },
  "39,16": {
   "revealed": false
  },
  "39,17": {
   "revealed": false
  },
  "39,18": {
   "revealed": false
  },
  "39,19": {
   "revealed": false
  },
  "39,20": {
   "revealed": false
  },
  "39,21": {
   "revealed": false
  },
  "39,22": {
   "revealed": false
  },
  "39,23": {
   "revealed": false
  },
  "39,24": {
   "revealed": false
  },
  "39,25": {
   "revealed": false
  },
  "39,26": {
   "revealed": false
  },
  "39,27": {
   "revealed": false
  },
  "39,28": {
   "revealed": false
  },
  "39,29": {
   "revealed": false
  },
  "39,30": {
   "revealed": false
  },
  "39,31": {
   "revealed": false
  },
  "39,32": {
   "revealed": false
  },
  "39,33": {
   "revealed": false
  },
  "39,34": {
   "revealed": false
  },
  "39,35": {
   "revealed": false
  },
  "39,36": {
   "revealed": false
  },
  "39,37": {
   "revealed": false
  },
  "39,38": {
   "revealed": false
  },
  "39,39": {
   "revealed": false
  },
  "39,40": {
   "revealed": false
  },
  "39,41": {
   "revealed": false
  },
  "39,42": {
   "revealed": false
  },
  "39,43": {
   "revealed": false
  },
  "39,44": {
   "revealed": false
  },
  "39,45": {
   "revealed": false
  },
  "39,46": {
   "revealed": false
  },
  "39,47": {
   "revealed": false
  },
  "39,48": {
   "revealed": false
  },
  "39,49": {
   "revealed": false
  },
  "40,0": {
   "revealed": false
  },
  "40,1": {
   "revealed": false
  },
  "40,2": {
   "revealed": false
  },
  "40,3": {
   "revealed": false
  },
  "40,4": {
   "revealed": false
  },
  "40,5": {
   "revealed": false
  },
  "40,6": {
   "revealed": false
  },
  "40,7": {
   "revealed": false
  },
  "40,8": {
   "revealed": false
  },
  "40,9": {
   "revealed": false
  },
  "40,10": {
   "revealed": false
  },
  "40,11": {
   "revealed": false
  },
  "40,12": {
   "revealed": false
  },
  "40,13": {
   "revealed": false
  },
  "40,14": {
   "revealed": false
  },
  "40,15": {
   "revealed": false
  },
  "40,16": {
   "revealed": false
  },
  "40,17": {
   "revealed": false
  },
  "40,18": {
   "revealed": false
  },
  "40,19": {
   "revealed": false
  },
  "40,20": {
   "revealed": false
  },
  "40,21": {
   "revealed": false
  },
  "40,22": {
   "revealed": false
  },
  "40,23": {
   "revealed": false
  },
  "40,24": {
   "revealed": false
  },
  "40,25": {
   "revealed": false
  },
  "40,26": {
   "revealed": false
  },
  "40,27": {
   "revealed": false
  },
  "40,28": {
   "revealed": false
  },
  "40,29": {
   "revealed": false
  },
  "40,30": {
   "revealed": false
  },
  "40,31": {
   "revealed": false
  },
  "40,32": {
   "revealed": false
  },
  "40,33": {
   "revealed": false
  },
  "40,34": {
   "revealed": false
  },
  "40,35": {
   "revealed": false
  },
  "40,36": {
   "revealed": false
  },
  "40,37": {
   "revealed": false
  },
  "40,38": {
   "revealed": false
  },
  "40,39": {
   "revealed": false
  },
  "40,40": {
   "revealed": false
  },
  "40,41": {
   "revealed": false
  },
  "40,42": {
   "revealed": false
  },
  "40,43": {
   "revealed": false
  },
  "40,44": {
   "revealed": false
  },
  "40,45": {
   "revealed": false
  },
  "40,46": {
   "revealed": false
  },
  "40,47": {
   "revealed": false
  },
  "40,48": {
   "revealed": false
  },
  "40,49": {
   "revealed": false
  },
  "41,0": {
   "revealed": false
  },
  "41,1": {
   "revealed": false
  },
  "41,2": {
   "revealed": false
  },
  "41,3": {
   "revealed": false
  },
  "41,4": {
   "revealed": false
  },
  "41,5": {
   "revealed": false
  },
  "41,6": {
   "revealed": false
  },
  "41,7": {
   "revealed": false
  },
  "41,8": {
   "revealed": false
  },
  "41,9": {
   "revealed": false
  },
  "41,10": {
   "revealed": false
  },
  "41,11": {
   "revealed": false
  },
  "41,12": {
   "revealed": false
  },
  "41,13": {
   "revealed": false
  },
  "41,14": {
   "revealed": false
  },
  "41,15": {
   "revealed": false
  },
  "41,16": {
   "revealed": false
  },
  "41,17": {
   "revealed": false
  },
  "41,18": {
   "revealed": false
  },
  "41,19": {
   "revealed": false
  },
  "41,20": {
   "revealed": false
  },
  "41,21": {
   "revealed": false
  },
  "41,22": {
   "revealed": false
  },
  "41,23": {
   "revealed": false
  },
  "41,24": {
   "revealed": false
  },
  "41,25": {
   "revealed": false
  },
  "41,26": {
   "revealed": false
  },
  "41,27": {
   "revealed": false
  },
  "41,28": {
   "revealed": false
  },
  "41,29": {
   "revealed": false
  },
  "41,30": {
   "revealed": false
  },
  "41,31": {
   "revealed": false
  },
  "41,32": {
   "revealed": false
  },
  "41,33": {
   "revealed": false
  },
  "41,34": {
   "revealed": false
  },
  "41,35": {
   "revealed": false
  },
  "41,36": {
   "revealed": false
  },
  "41,37": {
   "revealed": false
  },
  "41,38": {
   "revealed": false
  },
  "41,39": {
   "revealed": false
  },
  "41,40": {
   "revealed": false
  },
  "41,41": {
   "revealed": false
  },
  "41,42": {
   "revealed": false
  },
  "41,43": {
   "revealed": false
  },
  "41,44": {
   "revealed": false
  },
  "41,45": {
   "revealed": false
  },
  "41,46": {
   "revealed": false
  },
  "41,47": {
   "revealed": false
  },
  "41,48": {
   "revealed": false
  },
  "41,49": {
   "revealed": false
  },
  "42,0": {
   "revealed": false
  },
  "42,1": {
   "revealed": false
  },
  "42,2": {
   "revealed": false
  },
  "42,3": {
   "revealed": false
  },
  "42,4": {
   "revealed": false
  },
  "42,5": {
   "revealed": false
  },
  "42,6": {
   "revealed": false
  },
  "42,7": {
   "revealed": false
  },
  "42,8": {
   "revealed": false
  },
  "42,9": {
   "revealed": false
  },
  "42,10": {
   "revealed": false
  },
  "42,11": {
   "revealed": false
  },
  "42,12": {
   "revealed": false
  },
  "42,13": {
   "revealed": false
  },
  "42,14": {
   "revealed": false
  },
  "42,15": {
   "revealed": false
  },
  "42,16": {
   "revealed": false
  },
  "42,17": {
   "revealed": false
  },
  "42,18": {
   "revealed": false
  },
  "42,19": {
   "revealed": false
  },
  "42,20": {
   "revealed": false
  },
  "42,21": {
   "revealed": false
  },
  "42,22": {
   "revealed": false
  },
  "42,23": {
   "revealed": false
  },
  "42,24": {
   "revealed": false
  },
  "42,25": {
   "revealed": false
  },
  "42,26": {
   "revealed": false
  },
  "42,27": {
   "revealed": false
  },
  "42,28": {
   "revealed": false
  },
  "42,29": {
   "revealed": false
  },
  "42,30": {
   "revealed": false
  },
  "42,31": {
   "revealed": false
  },
  "42,32": {
   "revealed": false
  },
  "42,33": {
   "revealed": false
  },
  "42,34": {
   "revealed": false
  },
  "42,35": {
   "revealed": false
  },
  "42,36": {
   "revealed": false
  },
  "42,37": {
   "revealed": false
  },
  "42,38": {
   "revealed": false
  },
  "42,39": {
   "revealed": false
  },
  "42,40": {
   "revealed": false
  },
  "42,41": {
   "revealed": false
  },
  "42,42": {
   "revealed": false
  },
  "42,43": {
   "revealed": false
  },
  "42,44": {
   "revealed": false
  },
  "42,45": {
   "revealed": false
  },
  "42,46": {
   "revealed": false
  },
  "42,47": {
   "revealed": false
  },
  "42,48": {
   "revealed": false
  },
  "42,49": {
   "revealed": false
  },
  "43,0": {
   "revealed": false
  },
  "43,1": {
   "revealed": false
  },
  "43,2": {
   "revealed": false
  },
  "43,3": {
   "revealed": false
  },
  "43,4": {
   "revealed": false
  },
  "43,5": {
   "revealed": false
  },
  "43,6": {
   "revealed": false
  },
  "43,7": {
   "revealed": false
  },
  "43,8": {
   "revealed": false
  },
  "43,9": {
   "revealed": false
  },
  "43,10": {
   "revealed": false
  },
  "43,11": {
   "revealed": false
  },
  "43,12": {
   "revealed": false
  },
  "43,13": {
   "revealed": false
  },
  "43,14": {
   "revealed": false
  },
  "43,15": {
   "revealed": false
  },
  "43,16": {
   "revealed": false
  },
  "43,17": {
   "revealed": false
  },
  "43,18": {
   "revealed": false
  },
  "43,19": {
   "revealed": false
  },
  "43,20": {
   "revealed": false
  },
  "43,21": {
   "revealed": false
  },
  "43,22": {
   "revealed": false
  },
  "43,23": {
   "revealed": false
  },
  "43,24": {
   "revealed": false
  },
  "43,25": {
   "revealed": false
  },
  "43,26": {
   "revealed": false
  },
  "43,27": {
   "revealed": false
  },
  "43,28": {
   "revealed": false
  },
  "43,29": {
   "revealed": false
  },
  "43,30": {
   "revealed": false
  },
  "43,31": {
   "revealed": false
  },
  "43,32": {
   "revealed": false
  },
  "43,33": {
   "revealed": false
  },
  "43,34": {
   "revealed": false
  },
  "43,35": {
   "revealed": false
  },
  "43,36": {
   "revealed": false
  },
  "43,37": {
   "revealed": false
  },
  "43,38": {
   "revealed": false
  },
  "43,39": {
   "revealed": false
  },
  "43,40": {
   "revealed": false
  },
  "43,41": {
   "revealed": false
  },
  "43,42": {
   "revealed": false
  },
  "43,43": {
   "revealed": false
  },
  "43,44": {
   "revealed": false
  },
  "43,45": {
   "revealed": false
  },
  "43,46": {
   "revealed": false
  },
  "43,47": {
   "revealed": false
  },
  "43,48": {
   "revealed": false
  },
  "43,49": {
   "revealed": false
  },
  "44,0": {
   "revealed": false
  },
  "44,1": {
   "revealed": false
  },
  "44,2": {
   "revealed": false
  },
  "44,3": {
   "revealed": false
  },
  "44,4": {
   "revealed": false
  },
  "44,5": {
   "revealed": false
  },
  "44,6": {
   "revealed": false
  },
  "44,7": {
   "revealed": false
  },
  "44,8": {
   "revealed": false
  },
  "44,9": {
   "revealed": false
  },
  "44,10": {
   "revealed": false
  },
  "44,11": {
   "revealed": false
  },
  "44,12": {
   "revealed": false
  },
  "44,13": {
   "revealed": false
  },
  "44,14": {
   "revealed": false
  },
  "44,15": {
   "revealed": false
  },
  "44,16": {
   "revealed": false
  },
  "44,17": {
   "revealed": false
  },
  "44,18": {
   "revealed": false
  },
  "44,19": {
   "revealed": false
  },
  "44,20": {
   "revealed": false
  },
  "44,21": {
   "revealed": false
  },
  "44,22": {
   "revealed": false
  },
  "44,23": {
   "revealed": false
  },
  "44,24": {
   "revealed": false
  },
  "44,25": {
   "revealed": false
  },
  "44,26": {
   "revealed": false
  },
  "44,27": {
   "revealed": false
  },
  "44,28": {
   "revealed": false
  },
  "44,29": {
   "revealed": false
  },
  "44,30": {
   "revealed": false
  },
  "44,31": {
   "revealed": false
  },
  "44,32": {
   "revealed": false
  },
  "44,33": {
   "revealed": false
  },
  "44,34": {
   "revealed": false
  },
  "44,35": {
   "revealed": false
  },
  "44,36": {
   "revealed": false
  },
  "44,37": {
   "revealed": false
  },
  "44,38": {
   "revealed": false
  },
  "44,39": {
   "revealed": false
  },
  "44,40": {
   "revealed": false
  },
  "44,41": {
   "revealed": false
  },
  "44,42": {
   "revealed": false
  },
  "44,43": {
   "revealed": false
  },
  "44,44": {
   "revealed": false
  },
  "44,45": {
   "revealed": false
  },
  "44,46": {
   "revealed": false
  },
  "44,47": {
   "revealed": false
  },
  "44,48": {
   "revealed": false
  },
  "44,49": {
   "revealed": false
  },
  "45,0": {
   "revealed": false
  },
  "45,1": {
   "revealed": false
  },
  "45,2": {
   "revealed": false
  },
  "45,3": {
   "revealed": false
  },
  "45,4": {
   "revealed": false
  },
  "45,5": {
   "revealed": false
  },
  "45,6": {
   "revealed": false
  },
  "45,7": {
   "revealed": false
  },
  "45,8": {
   "revealed": false
  },
  "45,9": {
   "revealed": false
  },
  "45,10": {
   "revealed": false
  },
  "45,11": {
   "revealed": false
  },
  "45,12": {
   "revealed": false
  },
  "45,13": {
   "revealed": false
  },
  "45,14": {
   "revealed": false
  },
  "45,15": {
   "revealed": false
  },
  "45,16": {
   "revealed": false
  },
  "45,17": {
   "revealed": false
  },
  "45,18": {
   "revealed": false
  },
  "45,19": {
   "revealed": false
  },
  "45,20": {
   "revealed": false
  },
  "45,21": {
   "revealed": false
  },
  "45,22": {
   "revealed": false
  },
  "45,23": {
   "revealed": false
  },
  "45,24": {
   "revealed": false
  },
  "45,25": {
   "revealed": false
  },
  "45,26": {
   "revealed": false
  },
  "45,27": {
   "revealed": false
  },
  "45,28": {
   "revealed": false
  },
  "45,29": {
   "revealed": false
  },
  "45,30": {
   "revealed": false
  },
  "45,31": {
   "revealed": false
  },
  "45,32": {
   "revealed": false
  },
  "45,33": {
   "revealed": false
  },
  "45,34": {
   "revealed": false
  },
  "45,35": {
   "revealed": false
  },
  "45,36": {
   "revealed": false
  },
  "45,37": {
   "revealed": false
  },
  "45,38": {
   "revealed": false
  },
  "45,39": {
   "revealed": false
  },
  "45,40": {
   "revealed": false
  },
  "45,41": {
   "revealed": false
  },
  "45,42": {
   "revealed": false
  },
  "45,43": {
   "revealed": false
  },
  "45,44": {
   "revealed": false
  },
  "45,45": {
   "revealed": false
  },
  "45,46": {
   "revealed": false
  },
  "45,47": {
   "revealed": false
  },
  "45,48": {
   "revealed": false
  },
  "45,49": {
   "revealed": false
  },
  "46,0": {
   "revealed": false
  },
  "46,1": {
   "revealed": false
  },
  "46,2": {
   "revealed": false
  },
  "46,3": {
   "revealed": false
  },
  "46,4": {
   "revealed": false
  },
  "46,5": {
   "revealed": false
  },
  "46,6": {
   "revealed": false
  },
  "46,7": {
   "revealed": false
  },
  "46,8": {
   "revealed": false
  },
  "46,9": {
   "revealed": false
  },
  "46,10": {
   "revealed": false
  },
  "46,11": {
   "revealed": false
  },
  "46,12": {
   "revealed": false
  },
  "46,13": {
   "revealed": false
  },
  "46,14": {
   "revealed": false
  },
  "46,15": {
   "revealed": false
  },
  "46,16": {
   "revealed": false
  },
  "46,17": {
   "revealed": false
  },
  "46,18": {
   "revealed": false
  },
  "46,19": {
   "revealed": false
  },
  "46,20": {
   "revealed": false
  },
  "46,21": {
   "revealed": false
  },
  "46,22": {
   "revealed": false
  },
  "46,23": {
   "revealed": false
  },
  "46,24": {
   "revealed": false
  },
  "46,25": {
   "revealed": false
  },
  "46,26": {
   "revealed": false
  },
  "46,27": {
   "revealed": false
  },
  "46,28": {
   "revealed": false
  },
  "46,29": {
   "revealed": false
  },
  "46,30": {
   "revealed": false
  },
  "46,31": {
   "revealed": false
  },
  "46,32": {
   "revealed": false
  },
  "46,33": {
   "revealed": false
  },
  "46,34": {
   "revealed": false
  },
  "46,35": {
   "revealed": false
  },
  "46,36": {
   "revealed": false
  },
  "46,37": {
   "revealed": false
  },
  "46,38": {
   "revealed": false
  },
  "46,39": {
   "revealed": false
  },
  "46,40": {
   "revealed": false
  },
  "46,41": {
   "revealed": false
  },
  "46,42": {
   "revealed": false
  },
  "46,43": {
   "revealed": false
  },
  "46,44": {
   "revealed": false
  },
  "46,45": {
   "revealed": false
  },
  "46,46": {
   "revealed": false
  },
  "46,47": {
   "revealed": false
  },
  "46,48": {
   "revealed": false
  },
  "46,49": {
   "revealed": false
  },
  "47,0": {
   "revealed": false
  },
  "47,1": {
   "revealed": false
  },
  "47,2": {
   "revealed": false
  },
  "47,3": {
   "revealed": false
  },
  "47,4": {
   "revealed": false
  },
  "47,5": {
   "revealed": false
  },
  "47,6": {
   "revealed": false
  },
  "47,7": {
   "revealed": false
  },
  "47,8": {
   "revealed": false
  },
  "47,9": {
   "revealed": false
  },
  "47,10": {
   "revealed": false
  },
  "47,11": {
   "revealed": false
  },
  "47,12": {
   "revealed": false
  },
  "47,13": {
   "revealed": false
  },
  "47,14": {
   "revealed": false
  },
  "47,15": {
   "revealed": false
  },
  "47,16": {
   "revealed": false
  },
  "47,17": {
   "revealed": false
  },
  "47,18": {
   "revealed": false
  },
  "47,19": {
   "revealed": false
  },
  "47,20": {
   "revealed": false
  },
  "47,21": {
   "revealed": false
  },
  "47,22": {
   "revealed": false
  },
  "47,23": {
   "revealed": false
  },
  "47,24": {
   "revealed": false
  },
  "47,25": {
   "revealed": false
  },
  "47,26": {
   "revealed": false
  },
  "47,27": {
   "revealed": false
  },
  "47,28": {
   "revealed": false
  },
  "47,29": {
   "revealed": false
  },
  "47,30": {
   "revealed": false
  },
  "47,31": {
   "revealed": false
  },
  "47,32": {
   "revealed": false
  },
  "47,33": {
   "revealed": false
  },
  "47,34": {
   "revealed": false
  },
  "47,35": {
   "revealed": false
  },
  "47,36": {
   "revealed": false
  },
  "47,37": {
   "revealed": false
  },
  "47,38": {
   "revealed": false
  },
  "47,39": {
   "revealed": false
  },
  "47,40": {
   "revealed": false
  },
  "47,41": {
   "revealed": false
  },
  "47,42": {
   "revealed": false
  },
  "47,43": {
   "revealed": false
  },
  "47,44": {
   "revealed": false
  },
  "47,45": {
   "revealed": false
  },
  "47,46": {
   "revealed": false
  },
  "47,47": {
   "revealed": false
  },
  "47,48": {
   "revealed": false
  },
  "47,49": {
   "revealed": false
  },
  "48,0": {
   "revealed": false
  },
  "48,1": {
   "revealed": false
  },
  "48,2": {
   "revealed": false
  },
  "48,3": {
   "revealed": false
  },
  "48,4": {
   "revealed": false
  },
  "48,5": {
   "revealed": false
  },
  "48,6": {
   "revealed": false
  },
  "48,7": {
   "revealed": false
  },
  "48,8": {
   "revealed": false
  },
  "48,9": {
   "revealed": false
  },
  "48,10": {
   "revealed": false
  },
  "48,11": {
   "revealed": false
  },
  "48,12": {
   "revealed": false
  },
  "48,13": {
   "revealed": false
  },
  "48,14": {
   "revealed": false
  },
  "48,15": {
   "revealed": false
  },
  "48,16": {
   "revealed": false
  },
  "48,17": {
   "revealed": false
  },
  "48,18": {
   "revealed": false
  },
  "48,19": {
   "revealed": false
  },
  "48,20": {
   "revealed": false
  },
  "48,21": {
   "revealed": false
  },
  "48,22": {
   "revealed": false
  },
  "48,23": {
   "revealed": false
  },
  "48,24": {
   "revealed": false
  },
  "48,25": {
   "revealed": false
  },
  "48,26": {
   "revealed": false
  },
  "48,27": {
   "revealed": false
  },
  "48,28": {
   "revealed": false
  },
  "48,29": {
   "revealed": false
  },
  "48,30": {
   "revealed": false
  },
  "48,31": {
   "revealed": false
  },
  "48,32": {
   "revealed": false
  },
  "48,33": {
   "revealed": false
  },
  "48,34": {
   "revealed": false
  },
  "48,35": {
   "revealed": false
  },
  "48,36": {
   "revealed": false
  },
  "48,37": {
   "revealed": false
  },
  "48,38": {
   "revealed": false
  },
  "48,39": {
   "revealed": false
  },
  "48,40": {
   "revealed": false
  },
  "48,41": {
   "revealed": false
  },
  "48,42": {
   "revealed": false
  },
  "48,43": {
   "revealed": false
  },
  "48,44": {
   "revealed": false
  },
  "48,45": {
   "revealed": false
  },
  "48,46": {
   "revealed": false
  },
  "48,47": {
   "revealed": false
  },
  "48,48": {
   "revealed": false
  },
  "48,49": {
   "revealed": false
  },
  "49,0": {
   "revealed": false
  },
  "49,1": {
   "revealed": false
  },
  "49,2": {
   "revealed": false
  },
  "49,3": {
   "revealed": false
  },
  "49,4": {
   "revealed": false
  },
  "49,5": {
   "revealed": false
  },
  "49,6": {
   "revealed": false
  },
  "49,7": {
   "revealed": false
  },
  "49,8": {
   "revealed": false
  },
  "49,9": {
   "revealed": false
  },
  "49,10": {
   "revealed": false
  },
  "49,11": {
   "revealed": false
  },
  "49,12": {
   "revealed": false
  },
  "49,13": {
   "revealed": false
  },
  "49,14": {
   "revealed": false
  },
  "49,15": {
   "revealed": false
  },
  "49,16": {
   "revealed": false
  },
  "49,17": {
   "revealed": false
  },
  "49,18": {
   "revealed": false
  },
  "49,19": {
   "revealed": false
  },
  "49,20": {
   "revealed": false
  },
  "49,21": {
   "revealed": false
  },
  "49,22": {
   "revealed": false
  },
  "49,23": {
   "revealed": false
  },
  "49,24": {
   "revealed": false
  },
  "49,25": {
   "revealed": false
  },
  "49,26": {
   "revealed": false
  },
  "49,27": {
   "revealed": false
  },
  "49,28": {
   "revealed": false
  },
  "49,29": {
   "revealed": false
  },
  "49,30": {
   "revealed": false
  },
  "49,31": {
   "revealed": false
  },
  "49,32": {
   "revealed": false
  },
  "49,33": {
   "revealed": false
  },
  "49,34": {
   "revealed": false
  },
  "49,35": {
   "revealed": false
  },
  "49,36": {
   "revealed": false
  },
  "49,37": {
   "revealed": false
  },
  "49,38": {
   "revealed": false
  },
  "49,39": {
   "revealed": false
  },
  "49,40": {
   "revealed": false
  },
  "49,41": {
   "revealed": false
  },
  "49,42": {
   "revealed": false
  },
  "49,43": {
   "revealed": false
  },
  "49,44": {
   "revealed": false
  },
  "49,45": {
   "revealed": false
  },
  "49,46": {
   "revealed": false
  },
  "49,47": {
   "revealed": false
  },
  "49,48": {
   "revealed": false
  },
  "49,49": {
   "revealed": false
  }
 },
 "entities": {},
 "poiTypes": [
  "Settlement",
  "Ruins",
  "Dungeon",
  "Shrine",
  "Landmark",
  "Fortress",
  "Camp or Lair",
  "Natural Wonder",
  "Other"
 ],
 "rivers": {}
};
